<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/dialogflow/cx/v3beta1/entity_type.proto

namespace Google\Cloud\Dialogflow\Cx\V3beta1;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Dialogflow\Cx\V3beta1\EntityType\Entity instead.
     * @deprecated
     */
    class EntityType_Entity {}
}
class_exists(EntityType\Entity::class);
@trigger_error('Google\Cloud\Dialogflow\Cx\V3beta1\EntityType_Entity is deprecated and will be removed in the next major release. Use Google\Cloud\Dialogflow\Cx\V3beta1\EntityType\Entity instead', E_USER_DEPRECATED);

