<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/dataqna/v1alpha/question.proto

namespace Google\Cloud\DataQnA\V1alpha\ExecutionInfo;

use UnexpectedValueException;

/**
 * Enum of possible job execution statuses.
 *
 * Protobuf type <code>google.cloud.dataqna.v1alpha.ExecutionInfo.JobExecutionState</code>
 */
class JobExecutionState
{
    /**
     * No job execution was specified.
     *
     * Generated from protobuf enum <code>JOB_EXECUTION_STATE_UNSPECIFIED = 0;</code>
     */
    const JOB_EXECUTION_STATE_UNSPECIFIED = 0;
    /**
     * No job execution was requested, yet.
     *
     * Generated from protobuf enum <code>NOT_EXECUTED = 1;</code>
     */
    const NOT_EXECUTED = 1;
    /**
     * The job is running.
     *
     * Generated from protobuf enum <code>RUNNING = 2;</code>
     */
    const RUNNING = 2;
    /**
     * The job completed successfully.
     *
     * Generated from protobuf enum <code>SUCCEEDED = 3;</code>
     */
    const SUCCEEDED = 3;
    /**
     * The job completed unsuccessfully.
     *
     * Generated from protobuf enum <code>FAILED = 4;</code>
     */
    const FAILED = 4;

    private static $valueToName = [
        self::JOB_EXECUTION_STATE_UNSPECIFIED => 'JOB_EXECUTION_STATE_UNSPECIFIED',
        self::NOT_EXECUTED => 'NOT_EXECUTED',
        self::RUNNING => 'RUNNING',
        self::SUCCEEDED => 'SUCCEEDED',
        self::FAILED => 'FAILED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(JobExecutionState::class, \Google\Cloud\DataQnA\V1alpha\ExecutionInfo_JobExecutionState::class);

