<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v4/resources/domain_category.proto

namespace GPBMetadata\Google\Ads\Googleads\V4\Resources;

class DomainCategory
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();
        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        \GPBMetadata\Google\Api\Http::initOnce();
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\Resource::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        $pool->internalAddGeneratedFile(
            '
Û
7google/ads/googleads/v4/resources/domain_category.proto!google.ads.googleads.v4.resourcesgoogle/api/resource.protogoogle/protobuf/wrappers.protogoogle/api/annotations.proto"∞
DomainCategoryF
resource_name (	B/‡A˙A)
\'googleads.googleapis.com/DomainCategoryY
campaign (2.google.protobuf.StringValueB)‡A˙A#
!googleads.googleapis.com/Campaign3
category (2.google.protobuf.StringValueB‡A8
language_code (2.google.protobuf.StringValueB‡A1
domain (2.google.protobuf.StringValueB‡A<
coverage_fraction (2.google.protobuf.DoubleValueB‡A7
category_rank (2.google.protobuf.Int64ValueB‡A5
has_children (2.google.protobuf.BoolValueB‡AD
recommended_cpc_bid_micros	 (2.google.protobuf.Int64ValueB‡A:eÍAb
\'googleads.googleapis.com/DomainCategory7customers/{customer}/domainCategories/{domain_category}BÄ
%com.google.ads.googleads.v4.resourcesBDomainCategoryProtoPZJgoogle.golang.org/genproto/googleapis/ads/googleads/v4/resources;resources¢GAA™!Google.Ads.GoogleAds.V4.Resources !Google\\Ads\\GoogleAds\\V4\\ResourcesÍ%Google::Ads::GoogleAds::V4::Resourcesbproto3'
        , true);
        static::$is_initialized = true;
    }
}

