<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/datafusion/v1beta1/v1beta1.proto

namespace Google\Cloud\DataFusion\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * List namespaces request.
 *
 * Generated from protobuf message <code>google.cloud.datafusion.v1beta1.ListNamespacesRequest</code>
 */
class ListNamespacesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The instance to list its namespaces.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     */
    protected $parent = '';
    /**
     * The maximum number of items to return.
     *
     * Generated from protobuf field <code>int32 page_size = 2;</code>
     */
    protected $page_size = 0;
    /**
     * The next_page_token value to use if there are additional
     * results to retrieve for this list request.
     *
     * Generated from protobuf field <code>string page_token = 3;</code>
     */
    protected $page_token = '';
    /**
     * By default, only basic information about a namespace is returned
     * (e.g. name). When `NAMESPACE_VIEW_FULL` is specified, additional
     * information associated with a namespace gets returned
     * (e.g. IAM policy set on the namespace)
     *
     * Generated from protobuf field <code>.google.cloud.datafusion.v1beta1.NamespaceView view = 4;</code>
     */
    protected $view = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Required. The instance to list its namespaces.
     *     @type int $page_size
     *           The maximum number of items to return.
     *     @type string $page_token
     *           The next_page_token value to use if there are additional
     *           results to retrieve for this list request.
     *     @type int $view
     *           By default, only basic information about a namespace is returned
     *           (e.g. name). When `NAMESPACE_VIEW_FULL` is specified, additional
     *           information associated with a namespace gets returned
     *           (e.g. IAM policy set on the namespace)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Datafusion\V1Beta1\V1Beta1::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The instance to list its namespaces.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Required. The instance to list its namespaces.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * The maximum number of items to return.
     *
     * Generated from protobuf field <code>int32 page_size = 2;</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * The maximum number of items to return.
     *
     * Generated from protobuf field <code>int32 page_size = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     * The next_page_token value to use if there are additional
     * results to retrieve for this list request.
     *
     * Generated from protobuf field <code>string page_token = 3;</code>
     * @return string
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    /**
     * The next_page_token value to use if there are additional
     * results to retrieve for this list request.
     *
     * Generated from protobuf field <code>string page_token = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;

        return $this;
    }

    /**
     * By default, only basic information about a namespace is returned
     * (e.g. name). When `NAMESPACE_VIEW_FULL` is specified, additional
     * information associated with a namespace gets returned
     * (e.g. IAM policy set on the namespace)
     *
     * Generated from protobuf field <code>.google.cloud.datafusion.v1beta1.NamespaceView view = 4;</code>
     * @return int
     */
    public function getView()
    {
        return $this->view;
    }

    /**
     * By default, only basic information about a namespace is returned
     * (e.g. name). When `NAMESPACE_VIEW_FULL` is specified, additional
     * information associated with a namespace gets returned
     * (e.g. IAM policy set on the namespace)
     *
     * Generated from protobuf field <code>.google.cloud.datafusion.v1beta1.NamespaceView view = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setView($var)
    {
        GPBUtil::checkEnum($var, \Google\Cloud\DataFusion\V1beta1\NamespaceView::class);
        $this->view = $var;

        return $this;
    }

}

