// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/dialogflow/v2/participant.proto

package com.google.cloud.dialogflow.v2;

public interface AudioInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.dialogflow.v2.AudioInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. Instructs the speech recognizer how to process the speech audio.
   * </pre>
   *
   * <code>.google.cloud.dialogflow.v2.InputAudioConfig config = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <pre>
   * Required. Instructs the speech recognizer how to process the speech audio.
   * </pre>
   *
   * <code>.google.cloud.dialogflow.v2.InputAudioConfig config = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The config.
   */
  com.google.cloud.dialogflow.v2.InputAudioConfig getConfig();
  /**
   * <pre>
   * Required. Instructs the speech recognizer how to process the speech audio.
   * </pre>
   *
   * <code>.google.cloud.dialogflow.v2.InputAudioConfig config = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.cloud.dialogflow.v2.InputAudioConfigOrBuilder getConfigOrBuilder();

  /**
   * <pre>
   * Required. The natural language speech audio to be processed.
   * A single request can contain up to 1 minute of speech audio data.
   * The transcribed text cannot contain more than 256 bytes.
   * </pre>
   *
   * <code>bytes audio = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The audio.
   */
  com.google.protobuf.ByteString getAudio();
}
