<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/dialogflow/cx/v3/session.proto

namespace Google\Cloud\Dialogflow\Cx\V3;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Dialogflow\Cx\V3\Match\MatchType instead.
     * @deprecated
     */
    class Match_MatchType {}
}
class_exists(Match\MatchType::class);
@trigger_error('Google\Cloud\Dialogflow\Cx\V3\Match_MatchType is deprecated and will be removed in the next major release. Use Google\Cloud\Dialogflow\Cx\V3\Match\MatchType instead', E_USER_DEPRECATED);

