<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/dialogflow/cx/v3/response_message.proto

namespace Google\Cloud\Dialogflow\Cx\V3;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Dialogflow\Cx\V3\ResponseMessage\MixedAudio instead.
     * @deprecated
     */
    class ResponseMessage_MixedAudio {}
}
class_exists(ResponseMessage\MixedAudio::class);
@trigger_error('Google\Cloud\Dialogflow\Cx\V3\ResponseMessage_MixedAudio is deprecated and will be removed in the next major release. Use Google\Cloud\Dialogflow\Cx\V3\ResponseMessage\MixedAudio instead', E_USER_DEPRECATED);

