// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/cloud/vision/v1p3beta1/product_search.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Cloud.Vision.V1P3Beta1 {

  /// <summary>Holder for reflection information generated from google/cloud/vision/v1p3beta1/product_search.proto</summary>
  public static partial class ProductSearchReflection {

    #region Descriptor
    /// <summary>File descriptor for google/cloud/vision/v1p3beta1/product_search.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProductSearchReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjJnb29nbGUvY2xvdWQvdmlzaW9uL3YxcDNiZXRhMS9wcm9kdWN0X3NlYXJj",
            "aC5wcm90bxIdZ29vZ2xlLmNsb3VkLnZpc2lvbi52MXAzYmV0YTEaHGdvb2ds",
            "ZS9hcGkvYW5ub3RhdGlvbnMucHJvdG8aGWdvb2dsZS9hcGkvcmVzb3VyY2Uu",
            "cHJvdG8aLGdvb2dsZS9jbG91ZC92aXNpb24vdjFwM2JldGExL2dlb21ldHJ5",
            "LnByb3RvGjpnb29nbGUvY2xvdWQvdmlzaW9uL3YxcDNiZXRhMS9wcm9kdWN0",
            "X3NlYXJjaF9zZXJ2aWNlLnByb3RvGh9nb29nbGUvcHJvdG9idWYvdGltZXN0",
            "YW1wLnByb3RvItkDChNQcm9kdWN0U2VhcmNoUGFyYW1zEhQKDGNhdGFsb2df",
            "bmFtZRgBIAEoCRJGCghjYXRlZ29yeRgCIAEoDjI0Lmdvb2dsZS5jbG91ZC52",
            "aXNpb24udjFwM2JldGExLlByb2R1Y3RTZWFyY2hDYXRlZ29yeRIYChBwcm9k",
            "dWN0X2NhdGVnb3J5GAUgASgJElcKGG5vcm1hbGl6ZWRfYm91bmRpbmdfcG9s",
            "eRgDIAEoCzI1Lmdvb2dsZS5jbG91ZC52aXNpb24udjFwM2JldGExLk5vcm1h",
            "bGl6ZWRCb3VuZGluZ1BvbHkSQgoNYm91bmRpbmdfcG9seRgJIAEoCzIrLmdv",
            "b2dsZS5jbG91ZC52aXNpb24udjFwM2JldGExLkJvdW5kaW5nUG9seRJFCgR2",
            "aWV3GAQgASgOMjcuZ29vZ2xlLmNsb3VkLnZpc2lvbi52MXAzYmV0YTEuUHJv",
            "ZHVjdFNlYXJjaFJlc3VsdHNWaWV3EjoKC3Byb2R1Y3Rfc2V0GAYgASgJQiX6",
            "QSIKIHZpc2lvbi5nb29nbGVhcGlzLmNvbS9Qcm9kdWN0U2V0EhoKEnByb2R1",
            "Y3RfY2F0ZWdvcmllcxgHIAMoCRIOCgZmaWx0ZXIYCCABKAki7gMKFFByb2R1",
            "Y3RTZWFyY2hSZXN1bHRzEkYKCGNhdGVnb3J5GAEgASgOMjQuZ29vZ2xlLmNs",
            "b3VkLnZpc2lvbi52MXAzYmV0YTEuUHJvZHVjdFNlYXJjaENhdGVnb3J5EhgK",
            "EHByb2R1Y3RfY2F0ZWdvcnkYBCABKAkSLgoKaW5kZXhfdGltZRgCIAEoCzIa",
            "Lmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASUQoIcHJvZHVjdHMYAyADKAsy",
            "Py5nb29nbGUuY2xvdWQudmlzaW9uLnYxcDNiZXRhMS5Qcm9kdWN0U2VhcmNo",
            "UmVzdWx0cy5Qcm9kdWN0SW5mbxJLCgdyZXN1bHRzGAUgAygLMjouZ29vZ2xl",
            "LmNsb3VkLnZpc2lvbi52MXAzYmV0YTEuUHJvZHVjdFNlYXJjaFJlc3VsdHMu",
            "UmVzdWx0GkMKC1Byb2R1Y3RJbmZvEhIKCnByb2R1Y3RfaWQYASABKAkSEQoJ",
            "aW1hZ2VfdXJpGAIgASgJEg0KBXNjb3JlGAMgASgCGl8KBlJlc3VsdBI3Cgdw",
            "cm9kdWN0GAEgASgLMiYuZ29vZ2xlLmNsb3VkLnZpc2lvbi52MXAzYmV0YTEu",
            "UHJvZHVjdBINCgVzY29yZRgCIAEoAhINCgVpbWFnZRgDIAEoCSpVChVQcm9k",
            "dWN0U2VhcmNoQ2F0ZWdvcnkSJwojUFJPRFVDVF9TRUFSQ0hfQ0FURUdPUllf",
            "VU5TUEVDSUZJRUQQABIJCgVTSE9FUxABEggKBEJBR1MQAiovChhQcm9kdWN0",
            "U2VhcmNoUmVzdWx0c1ZpZXcSCQoFQkFTSUMQABIICgRGVUxMEAFCgQEKIWNv",
            "bS5nb29nbGUuY2xvdWQudmlzaW9uLnYxcDNiZXRhMUISUHJvZHVjdFNlYXJj",
            "aFByb3RvUAFaQ2dvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFw",
            "aXMvY2xvdWQvdmlzaW9uL3YxcDNiZXRhMTt2aXNpb274AQFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Google.Api.ResourceReflection.Descriptor, global::Google.Cloud.Vision.V1P3Beta1.GeometryReflection.Descriptor, global::Google.Cloud.Vision.V1P3Beta1.ProductSearchServiceReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory), typeof(global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResultsView), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Cloud.Vision.V1P3Beta1.ProductSearchParams), global::Google.Cloud.Vision.V1P3Beta1.ProductSearchParams.Parser, new[]{ "CatalogName", "Category", "ProductCategory", "NormalizedBoundingPoly", "BoundingPoly", "View", "ProductSet", "ProductCategories", "Filter" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResults), global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResults.Parser, new[]{ "Category", "ProductCategory", "IndexTime", "Products", "Results" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResults.Types.ProductInfo), global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResults.Types.ProductInfo.Parser, new[]{ "ProductId", "ImageUri", "Score" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResults.Types.Result), global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResults.Types.Result.Parser, new[]{ "Product", "Score", "Image" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Supported product search categories.
  /// </summary>
  public enum ProductSearchCategory {
    /// <summary>
    /// Default value used when a category is not specified.
    /// </summary>
    [pbr::OriginalName("PRODUCT_SEARCH_CATEGORY_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Shoes category.
    /// </summary>
    [pbr::OriginalName("SHOES")] Shoes = 1,
    /// <summary>
    /// Bags category.
    /// </summary>
    [pbr::OriginalName("BAGS")] Bags = 2,
  }

  /// <summary>
  /// Specifies the fields to include in product search results.
  /// </summary>
  public enum ProductSearchResultsView {
    /// <summary>
    /// Product search results contain only `product_category` and `product_id`.
    /// Default value.
    /// </summary>
    [pbr::OriginalName("BASIC")] Basic = 0,
    /// <summary>
    /// Product search results contain `product_category`, `product_id`,
    /// `image_uri`, and `score`.
    /// </summary>
    [pbr::OriginalName("FULL")] Full = 1,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Parameters for a product search request.
  /// </summary>
  public sealed partial class ProductSearchParams : pb::IMessage<ProductSearchParams>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProductSearchParams> _parser = new pb::MessageParser<ProductSearchParams>(() => new ProductSearchParams());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ProductSearchParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Cloud.Vision.V1P3Beta1.ProductSearchReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProductSearchParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProductSearchParams(ProductSearchParams other) : this() {
      catalogName_ = other.catalogName_;
      category_ = other.category_;
      productCategory_ = other.productCategory_;
      normalizedBoundingPoly_ = other.normalizedBoundingPoly_ != null ? other.normalizedBoundingPoly_.Clone() : null;
      boundingPoly_ = other.boundingPoly_ != null ? other.boundingPoly_.Clone() : null;
      view_ = other.view_;
      productSet_ = other.productSet_;
      productCategories_ = other.productCategories_.Clone();
      filter_ = other.filter_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProductSearchParams Clone() {
      return new ProductSearchParams(this);
    }

    /// <summary>Field number for the "catalog_name" field.</summary>
    public const int CatalogNameFieldNumber = 1;
    private string catalogName_ = "";
    /// <summary>
    /// The resource name of the catalog to search.
    ///
    /// Format is: `productSearch/catalogs/CATALOG_NAME`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CatalogName {
      get { return catalogName_; }
      set {
        catalogName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "category" field.</summary>
    public const int CategoryFieldNumber = 2;
    private global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory category_ = global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory.Unspecified;
    /// <summary>
    /// The category to search in.
    /// Optional. It is inferred by the system if it is not specified.
    /// [Deprecated] Use `product_category`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory Category {
      get { return category_; }
      set {
        category_ = value;
      }
    }

    /// <summary>Field number for the "product_category" field.</summary>
    public const int ProductCategoryFieldNumber = 5;
    private string productCategory_ = "";
    /// <summary>
    /// The product category to search in.
    /// Optional. It is inferred by the system if it is not specified.
    /// Supported values are `bag`, `shoe`, `sunglasses`, `dress`, `outerwear`,
    /// `skirt`, `top`, `shorts`, and `pants`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ProductCategory {
      get { return productCategory_; }
      set {
        productCategory_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "normalized_bounding_poly" field.</summary>
    public const int NormalizedBoundingPolyFieldNumber = 3;
    private global::Google.Cloud.Vision.V1P3Beta1.NormalizedBoundingPoly normalizedBoundingPoly_;
    /// <summary>
    /// The bounding polygon around the area of interest in the image.
    /// Optional. If it is not specified, system discretion will be applied.
    /// [Deprecated] Use `bounding_poly`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Cloud.Vision.V1P3Beta1.NormalizedBoundingPoly NormalizedBoundingPoly {
      get { return normalizedBoundingPoly_; }
      set {
        normalizedBoundingPoly_ = value;
      }
    }

    /// <summary>Field number for the "bounding_poly" field.</summary>
    public const int BoundingPolyFieldNumber = 9;
    private global::Google.Cloud.Vision.V1P3Beta1.BoundingPoly boundingPoly_;
    /// <summary>
    /// The bounding polygon around the area of interest in the image.
    /// Optional. If it is not specified, system discretion will be applied.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Cloud.Vision.V1P3Beta1.BoundingPoly BoundingPoly {
      get { return boundingPoly_; }
      set {
        boundingPoly_ = value;
      }
    }

    /// <summary>Field number for the "view" field.</summary>
    public const int ViewFieldNumber = 4;
    private global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResultsView view_ = global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResultsView.Basic;
    /// <summary>
    /// Specifies the verbosity of the  product search results.
    /// Optional. Defaults to `BASIC`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResultsView View {
      get { return view_; }
      set {
        view_ = value;
      }
    }

    /// <summary>Field number for the "product_set" field.</summary>
    public const int ProductSetFieldNumber = 6;
    private string productSet_ = "";
    /// <summary>
    /// The resource name of a
    /// [ProductSet][google.cloud.vision.v1p3beta1.ProductSet] to be searched for
    /// similar images.
    ///
    /// Format is:
    /// `projects/PROJECT_ID/locations/LOC_ID/productSets/PRODUCT_SET_ID`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ProductSet {
      get { return productSet_; }
      set {
        productSet_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "product_categories" field.</summary>
    public const int ProductCategoriesFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _repeated_productCategories_codec
        = pb::FieldCodec.ForString(58);
    private readonly pbc::RepeatedField<string> productCategories_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// The list of product categories to search in. Currently, we only consider
    /// the first category, and either "homegoods" or "apparel" should be
    /// specified.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> ProductCategories {
      get { return productCategories_; }
    }

    /// <summary>Field number for the "filter" field.</summary>
    public const int FilterFieldNumber = 8;
    private string filter_ = "";
    /// <summary>
    /// The filtering expression. This can be used to restrict search results based
    /// on Product labels. We currently support an AND of OR of key-value
    /// expressions, where each expression within an OR must have the same key.
    ///
    /// For example, "(color = red OR color = blue) AND brand = Google" is
    /// acceptable, but not "(color = red OR brand = Google)" or "color: red".
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Filter {
      get { return filter_; }
      set {
        filter_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ProductSearchParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ProductSearchParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CatalogName != other.CatalogName) return false;
      if (Category != other.Category) return false;
      if (ProductCategory != other.ProductCategory) return false;
      if (!object.Equals(NormalizedBoundingPoly, other.NormalizedBoundingPoly)) return false;
      if (!object.Equals(BoundingPoly, other.BoundingPoly)) return false;
      if (View != other.View) return false;
      if (ProductSet != other.ProductSet) return false;
      if(!productCategories_.Equals(other.productCategories_)) return false;
      if (Filter != other.Filter) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CatalogName.Length != 0) hash ^= CatalogName.GetHashCode();
      if (Category != global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory.Unspecified) hash ^= Category.GetHashCode();
      if (ProductCategory.Length != 0) hash ^= ProductCategory.GetHashCode();
      if (normalizedBoundingPoly_ != null) hash ^= NormalizedBoundingPoly.GetHashCode();
      if (boundingPoly_ != null) hash ^= BoundingPoly.GetHashCode();
      if (View != global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResultsView.Basic) hash ^= View.GetHashCode();
      if (ProductSet.Length != 0) hash ^= ProductSet.GetHashCode();
      hash ^= productCategories_.GetHashCode();
      if (Filter.Length != 0) hash ^= Filter.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CatalogName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CatalogName);
      }
      if (Category != global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Category);
      }
      if (normalizedBoundingPoly_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(NormalizedBoundingPoly);
      }
      if (View != global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResultsView.Basic) {
        output.WriteRawTag(32);
        output.WriteEnum((int) View);
      }
      if (ProductCategory.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ProductCategory);
      }
      if (ProductSet.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ProductSet);
      }
      productCategories_.WriteTo(output, _repeated_productCategories_codec);
      if (Filter.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Filter);
      }
      if (boundingPoly_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(BoundingPoly);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CatalogName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CatalogName);
      }
      if (Category != global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Category);
      }
      if (normalizedBoundingPoly_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(NormalizedBoundingPoly);
      }
      if (View != global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResultsView.Basic) {
        output.WriteRawTag(32);
        output.WriteEnum((int) View);
      }
      if (ProductCategory.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ProductCategory);
      }
      if (ProductSet.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ProductSet);
      }
      productCategories_.WriteTo(ref output, _repeated_productCategories_codec);
      if (Filter.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Filter);
      }
      if (boundingPoly_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(BoundingPoly);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CatalogName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CatalogName);
      }
      if (Category != global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Category);
      }
      if (ProductCategory.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProductCategory);
      }
      if (normalizedBoundingPoly_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NormalizedBoundingPoly);
      }
      if (boundingPoly_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BoundingPoly);
      }
      if (View != global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResultsView.Basic) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) View);
      }
      if (ProductSet.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProductSet);
      }
      size += productCategories_.CalculateSize(_repeated_productCategories_codec);
      if (Filter.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Filter);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ProductSearchParams other) {
      if (other == null) {
        return;
      }
      if (other.CatalogName.Length != 0) {
        CatalogName = other.CatalogName;
      }
      if (other.Category != global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory.Unspecified) {
        Category = other.Category;
      }
      if (other.ProductCategory.Length != 0) {
        ProductCategory = other.ProductCategory;
      }
      if (other.normalizedBoundingPoly_ != null) {
        if (normalizedBoundingPoly_ == null) {
          NormalizedBoundingPoly = new global::Google.Cloud.Vision.V1P3Beta1.NormalizedBoundingPoly();
        }
        NormalizedBoundingPoly.MergeFrom(other.NormalizedBoundingPoly);
      }
      if (other.boundingPoly_ != null) {
        if (boundingPoly_ == null) {
          BoundingPoly = new global::Google.Cloud.Vision.V1P3Beta1.BoundingPoly();
        }
        BoundingPoly.MergeFrom(other.BoundingPoly);
      }
      if (other.View != global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResultsView.Basic) {
        View = other.View;
      }
      if (other.ProductSet.Length != 0) {
        ProductSet = other.ProductSet;
      }
      productCategories_.Add(other.productCategories_);
      if (other.Filter.Length != 0) {
        Filter = other.Filter;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CatalogName = input.ReadString();
            break;
          }
          case 16: {
            Category = (global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory) input.ReadEnum();
            break;
          }
          case 26: {
            if (normalizedBoundingPoly_ == null) {
              NormalizedBoundingPoly = new global::Google.Cloud.Vision.V1P3Beta1.NormalizedBoundingPoly();
            }
            input.ReadMessage(NormalizedBoundingPoly);
            break;
          }
          case 32: {
            View = (global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResultsView) input.ReadEnum();
            break;
          }
          case 42: {
            ProductCategory = input.ReadString();
            break;
          }
          case 50: {
            ProductSet = input.ReadString();
            break;
          }
          case 58: {
            productCategories_.AddEntriesFrom(input, _repeated_productCategories_codec);
            break;
          }
          case 66: {
            Filter = input.ReadString();
            break;
          }
          case 74: {
            if (boundingPoly_ == null) {
              BoundingPoly = new global::Google.Cloud.Vision.V1P3Beta1.BoundingPoly();
            }
            input.ReadMessage(BoundingPoly);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            CatalogName = input.ReadString();
            break;
          }
          case 16: {
            Category = (global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory) input.ReadEnum();
            break;
          }
          case 26: {
            if (normalizedBoundingPoly_ == null) {
              NormalizedBoundingPoly = new global::Google.Cloud.Vision.V1P3Beta1.NormalizedBoundingPoly();
            }
            input.ReadMessage(NormalizedBoundingPoly);
            break;
          }
          case 32: {
            View = (global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResultsView) input.ReadEnum();
            break;
          }
          case 42: {
            ProductCategory = input.ReadString();
            break;
          }
          case 50: {
            ProductSet = input.ReadString();
            break;
          }
          case 58: {
            productCategories_.AddEntriesFrom(ref input, _repeated_productCategories_codec);
            break;
          }
          case 66: {
            Filter = input.ReadString();
            break;
          }
          case 74: {
            if (boundingPoly_ == null) {
              BoundingPoly = new global::Google.Cloud.Vision.V1P3Beta1.BoundingPoly();
            }
            input.ReadMessage(BoundingPoly);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Results for a product search request.
  /// </summary>
  public sealed partial class ProductSearchResults : pb::IMessage<ProductSearchResults>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProductSearchResults> _parser = new pb::MessageParser<ProductSearchResults>(() => new ProductSearchResults());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ProductSearchResults> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Cloud.Vision.V1P3Beta1.ProductSearchReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProductSearchResults() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProductSearchResults(ProductSearchResults other) : this() {
      category_ = other.category_;
      productCategory_ = other.productCategory_;
      indexTime_ = other.indexTime_ != null ? other.indexTime_.Clone() : null;
      products_ = other.products_.Clone();
      results_ = other.results_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProductSearchResults Clone() {
      return new ProductSearchResults(this);
    }

    /// <summary>Field number for the "category" field.</summary>
    public const int CategoryFieldNumber = 1;
    private global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory category_ = global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory.Unspecified;
    /// <summary>
    /// Product category.
    /// [Deprecated] Use `product_category`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory Category {
      get { return category_; }
      set {
        category_ = value;
      }
    }

    /// <summary>Field number for the "product_category" field.</summary>
    public const int ProductCategoryFieldNumber = 4;
    private string productCategory_ = "";
    /// <summary>
    /// Product category.
    /// Supported values are `bag` and `shoe`.
    /// [Deprecated] `product_category` is provided in each Product.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ProductCategory {
      get { return productCategory_; }
      set {
        productCategory_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "index_time" field.</summary>
    public const int IndexTimeFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp indexTime_;
    /// <summary>
    /// Timestamp of the index which provided these results. Changes made after
    /// this time are not reflected in the current results.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp IndexTime {
      get { return indexTime_; }
      set {
        indexTime_ = value;
      }
    }

    /// <summary>Field number for the "products" field.</summary>
    public const int ProductsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResults.Types.ProductInfo> _repeated_products_codec
        = pb::FieldCodec.ForMessage(26, global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResults.Types.ProductInfo.Parser);
    private readonly pbc::RepeatedField<global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResults.Types.ProductInfo> products_ = new pbc::RepeatedField<global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResults.Types.ProductInfo>();
    /// <summary>
    /// List of detected products.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResults.Types.ProductInfo> Products {
      get { return products_; }
    }

    /// <summary>Field number for the "results" field.</summary>
    public const int ResultsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResults.Types.Result> _repeated_results_codec
        = pb::FieldCodec.ForMessage(42, global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResults.Types.Result.Parser);
    private readonly pbc::RepeatedField<global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResults.Types.Result> results_ = new pbc::RepeatedField<global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResults.Types.Result>();
    /// <summary>
    /// List of results, one for each product match.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResults.Types.Result> Results {
      get { return results_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ProductSearchResults);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ProductSearchResults other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Category != other.Category) return false;
      if (ProductCategory != other.ProductCategory) return false;
      if (!object.Equals(IndexTime, other.IndexTime)) return false;
      if(!products_.Equals(other.products_)) return false;
      if(!results_.Equals(other.results_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Category != global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory.Unspecified) hash ^= Category.GetHashCode();
      if (ProductCategory.Length != 0) hash ^= ProductCategory.GetHashCode();
      if (indexTime_ != null) hash ^= IndexTime.GetHashCode();
      hash ^= products_.GetHashCode();
      hash ^= results_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Category != global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Category);
      }
      if (indexTime_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(IndexTime);
      }
      products_.WriteTo(output, _repeated_products_codec);
      if (ProductCategory.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ProductCategory);
      }
      results_.WriteTo(output, _repeated_results_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Category != global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Category);
      }
      if (indexTime_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(IndexTime);
      }
      products_.WriteTo(ref output, _repeated_products_codec);
      if (ProductCategory.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ProductCategory);
      }
      results_.WriteTo(ref output, _repeated_results_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Category != global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Category);
      }
      if (ProductCategory.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProductCategory);
      }
      if (indexTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(IndexTime);
      }
      size += products_.CalculateSize(_repeated_products_codec);
      size += results_.CalculateSize(_repeated_results_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ProductSearchResults other) {
      if (other == null) {
        return;
      }
      if (other.Category != global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory.Unspecified) {
        Category = other.Category;
      }
      if (other.ProductCategory.Length != 0) {
        ProductCategory = other.ProductCategory;
      }
      if (other.indexTime_ != null) {
        if (indexTime_ == null) {
          IndexTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        IndexTime.MergeFrom(other.IndexTime);
      }
      products_.Add(other.products_);
      results_.Add(other.results_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Category = (global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory) input.ReadEnum();
            break;
          }
          case 18: {
            if (indexTime_ == null) {
              IndexTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(IndexTime);
            break;
          }
          case 26: {
            products_.AddEntriesFrom(input, _repeated_products_codec);
            break;
          }
          case 34: {
            ProductCategory = input.ReadString();
            break;
          }
          case 42: {
            results_.AddEntriesFrom(input, _repeated_results_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Category = (global::Google.Cloud.Vision.V1P3Beta1.ProductSearchCategory) input.ReadEnum();
            break;
          }
          case 18: {
            if (indexTime_ == null) {
              IndexTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(IndexTime);
            break;
          }
          case 26: {
            products_.AddEntriesFrom(ref input, _repeated_products_codec);
            break;
          }
          case 34: {
            ProductCategory = input.ReadString();
            break;
          }
          case 42: {
            results_.AddEntriesFrom(ref input, _repeated_results_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ProductSearchResults message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      /// Information about a product.
      /// </summary>
      public sealed partial class ProductInfo : pb::IMessage<ProductInfo>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ProductInfo> _parser = new pb::MessageParser<ProductInfo>(() => new ProductInfo());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<ProductInfo> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResults.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ProductInfo() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ProductInfo(ProductInfo other) : this() {
          productId_ = other.productId_;
          imageUri_ = other.imageUri_;
          score_ = other.score_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ProductInfo Clone() {
          return new ProductInfo(this);
        }

        /// <summary>Field number for the "product_id" field.</summary>
        public const int ProductIdFieldNumber = 1;
        private string productId_ = "";
        /// <summary>
        /// Product ID.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string ProductId {
          get { return productId_; }
          set {
            productId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "image_uri" field.</summary>
        public const int ImageUriFieldNumber = 2;
        private string imageUri_ = "";
        /// <summary>
        /// The URI of the image which matched the query image.
        ///
        /// This field is returned only if `view` is set to `FULL` in
        /// the request.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string ImageUri {
          get { return imageUri_; }
          set {
            imageUri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "score" field.</summary>
        public const int ScoreFieldNumber = 3;
        private float score_;
        /// <summary>
        /// A confidence level on the match, ranging from 0 (no confidence) to
        /// 1 (full confidence).
        ///
        /// This field is returned only if `view` is set to `FULL` in
        /// the request.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public float Score {
          get { return score_; }
          set {
            score_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as ProductInfo);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(ProductInfo other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ProductId != other.ProductId) return false;
          if (ImageUri != other.ImageUri) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Score, other.Score)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (ProductId.Length != 0) hash ^= ProductId.GetHashCode();
          if (ImageUri.Length != 0) hash ^= ImageUri.GetHashCode();
          if (Score != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Score);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (ProductId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(ProductId);
          }
          if (ImageUri.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(ImageUri);
          }
          if (Score != 0F) {
            output.WriteRawTag(29);
            output.WriteFloat(Score);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (ProductId.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(ProductId);
          }
          if (ImageUri.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(ImageUri);
          }
          if (Score != 0F) {
            output.WriteRawTag(29);
            output.WriteFloat(Score);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (ProductId.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ProductId);
          }
          if (ImageUri.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ImageUri);
          }
          if (Score != 0F) {
            size += 1 + 4;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(ProductInfo other) {
          if (other == null) {
            return;
          }
          if (other.ProductId.Length != 0) {
            ProductId = other.ProductId;
          }
          if (other.ImageUri.Length != 0) {
            ImageUri = other.ImageUri;
          }
          if (other.Score != 0F) {
            Score = other.Score;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                ProductId = input.ReadString();
                break;
              }
              case 18: {
                ImageUri = input.ReadString();
                break;
              }
              case 29: {
                Score = input.ReadFloat();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                ProductId = input.ReadString();
                break;
              }
              case 18: {
                ImageUri = input.ReadString();
                break;
              }
              case 29: {
                Score = input.ReadFloat();
                break;
              }
            }
          }
        }
        #endif

      }

      /// <summary>
      /// Information about a product.
      /// </summary>
      public sealed partial class Result : pb::IMessage<Result>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Result> _parser = new pb::MessageParser<Result>(() => new Result());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Result> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Google.Cloud.Vision.V1P3Beta1.ProductSearchResults.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Result() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Result(Result other) : this() {
          product_ = other.product_ != null ? other.product_.Clone() : null;
          score_ = other.score_;
          image_ = other.image_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Result Clone() {
          return new Result(this);
        }

        /// <summary>Field number for the "product" field.</summary>
        public const int ProductFieldNumber = 1;
        private global::Google.Cloud.Vision.V1P3Beta1.Product product_;
        /// <summary>
        /// The Product.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Google.Cloud.Vision.V1P3Beta1.Product Product {
          get { return product_; }
          set {
            product_ = value;
          }
        }

        /// <summary>Field number for the "score" field.</summary>
        public const int ScoreFieldNumber = 2;
        private float score_;
        /// <summary>
        /// A confidence level on the match, ranging from 0 (no confidence) to
        /// 1 (full confidence).
        ///
        /// This field is returned only if `view` is set to `FULL` in
        /// the request.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public float Score {
          get { return score_; }
          set {
            score_ = value;
          }
        }

        /// <summary>Field number for the "image" field.</summary>
        public const int ImageFieldNumber = 3;
        private string image_ = "";
        /// <summary>
        /// The resource name of the image from the product that is the closest match
        /// to the query.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Image {
          get { return image_; }
          set {
            image_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Result);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Result other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(Product, other.Product)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Score, other.Score)) return false;
          if (Image != other.Image) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (product_ != null) hash ^= Product.GetHashCode();
          if (Score != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Score);
          if (Image.Length != 0) hash ^= Image.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (product_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(Product);
          }
          if (Score != 0F) {
            output.WriteRawTag(21);
            output.WriteFloat(Score);
          }
          if (Image.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Image);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (product_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(Product);
          }
          if (Score != 0F) {
            output.WriteRawTag(21);
            output.WriteFloat(Score);
          }
          if (Image.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(Image);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (product_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Product);
          }
          if (Score != 0F) {
            size += 1 + 4;
          }
          if (Image.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Image);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Result other) {
          if (other == null) {
            return;
          }
          if (other.product_ != null) {
            if (product_ == null) {
              Product = new global::Google.Cloud.Vision.V1P3Beta1.Product();
            }
            Product.MergeFrom(other.Product);
          }
          if (other.Score != 0F) {
            Score = other.Score;
          }
          if (other.Image.Length != 0) {
            Image = other.Image;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (product_ == null) {
                  Product = new global::Google.Cloud.Vision.V1P3Beta1.Product();
                }
                input.ReadMessage(Product);
                break;
              }
              case 21: {
                Score = input.ReadFloat();
                break;
              }
              case 26: {
                Image = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                if (product_ == null) {
                  Product = new global::Google.Cloud.Vision.V1P3Beta1.Product();
                }
                input.ReadMessage(Product);
                break;
              }
              case 21: {
                Score = input.ReadFloat();
                break;
              }
              case 26: {
                Image = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
