// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/cloud/retail/v2beta/user_event_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Cloud.Retail.V2Beta {

  /// <summary>Holder for reflection information generated from google/cloud/retail/v2beta/user_event_service.proto</summary>
  public static partial class UserEventServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for google/cloud/retail/v2beta/user_event_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserEventServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjNnb29nbGUvY2xvdWQvcmV0YWlsL3YyYmV0YS91c2VyX2V2ZW50X3NlcnZp",
            "Y2UucHJvdG8SGmdvb2dsZS5jbG91ZC5yZXRhaWwudjJiZXRhGhxnb29nbGUv",
            "YXBpL2Fubm90YXRpb25zLnByb3RvGhdnb29nbGUvYXBpL2NsaWVudC5wcm90",
            "bxofZ29vZ2xlL2FwaS9maWVsZF9iZWhhdmlvci5wcm90bxoZZ29vZ2xlL2Fw",
            "aS9odHRwYm9keS5wcm90bxouZ29vZ2xlL2Nsb3VkL3JldGFpbC92MmJldGEv",
            "ZXhwb3J0X2NvbmZpZy5wcm90bxouZ29vZ2xlL2Nsb3VkL3JldGFpbC92MmJl",
            "dGEvaW1wb3J0X2NvbmZpZy5wcm90bxotZ29vZ2xlL2Nsb3VkL3JldGFpbC92",
            "MmJldGEvcHVyZ2VfY29uZmlnLnByb3RvGitnb29nbGUvY2xvdWQvcmV0YWls",
            "L3YyYmV0YS91c2VyX2V2ZW50LnByb3RvGiNnb29nbGUvbG9uZ3J1bm5pbmcv",
            "b3BlcmF0aW9ucy5wcm90byJsChVXcml0ZVVzZXJFdmVudFJlcXVlc3QSEwoG",
            "cGFyZW50GAEgASgJQgPgQQISPgoKdXNlcl9ldmVudBgCIAEoCzIlLmdvb2ds",
            "ZS5jbG91ZC5yZXRhaWwudjJiZXRhLlVzZXJFdmVudEID4EECImEKF0NvbGxl",
            "Y3RVc2VyRXZlbnRSZXF1ZXN0EhMKBnBhcmVudBgBIAEoCUID4EECEhcKCnVz",
            "ZXJfZXZlbnQYAiABKAlCA+BBAhILCgN1cmkYAyABKAkSCwoDZXRzGAQgASgD",
            "IoICChdSZWpvaW5Vc2VyRXZlbnRzUmVxdWVzdBITCgZwYXJlbnQYASABKAlC",
            "A+BBAhJpChd1c2VyX2V2ZW50X3Jlam9pbl9zY29wZRgCIAEoDjJILmdvb2ds",
            "ZS5jbG91ZC5yZXRhaWwudjJiZXRhLlJlam9pblVzZXJFdmVudHNSZXF1ZXN0",
            "LlVzZXJFdmVudFJlam9pblNjb3BlImcKFFVzZXJFdmVudFJlam9pblNjb3Bl",
            "EicKI1VTRVJfRVZFTlRfUkVKT0lOX1NDT1BFX1VOU1BFQ0lGSUVEEAASEQoN",
            "Sk9JTkVEX0VWRU5UUxABEhMKD1VOSk9JTkVEX0VWRU5UUxACIj4KGFJlam9p",
            "blVzZXJFdmVudHNSZXNwb25zZRIiChpyZWpvaW5lZF91c2VyX2V2ZW50c19j",
            "b3VudBgBIAEoAyIaChhSZWpvaW5Vc2VyRXZlbnRzTWV0YWRhdGEy+wkKEFVz",
            "ZXJFdmVudFNlcnZpY2USwwEKDldyaXRlVXNlckV2ZW50EjEuZ29vZ2xlLmNs",
            "b3VkLnJldGFpbC52MmJldGEuV3JpdGVVc2VyRXZlbnRSZXF1ZXN0GiUuZ29v",
            "Z2xlLmNsb3VkLnJldGFpbC52MmJldGEuVXNlckV2ZW50IleC0+STAlEiQy92",
            "MmJldGEve3BhcmVudD1wcm9qZWN0cy8qL2xvY2F0aW9ucy8qL2NhdGFsb2dz",
            "Lyp9L3VzZXJFdmVudHM6d3JpdGU6CnVzZXJfZXZlbnQSrAEKEENvbGxlY3RV",
            "c2VyRXZlbnQSMy5nb29nbGUuY2xvdWQucmV0YWlsLnYyYmV0YS5Db2xsZWN0",
            "VXNlckV2ZW50UmVxdWVzdBoULmdvb2dsZS5hcGkuSHR0cEJvZHkiTYLT5JMC",
            "RxJFL3YyYmV0YS97cGFyZW50PXByb2plY3RzLyovbG9jYXRpb25zLyovY2F0",
            "YWxvZ3MvKn0vdXNlckV2ZW50czpjb2xsZWN0EpYCCg9QdXJnZVVzZXJFdmVu",
            "dHMSMi5nb29nbGUuY2xvdWQucmV0YWlsLnYyYmV0YS5QdXJnZVVzZXJFdmVu",
            "dHNSZXF1ZXN0Gh0uZ29vZ2xlLmxvbmdydW5uaW5nLk9wZXJhdGlvbiKvAYLT",
            "5JMCSCJDL3YyYmV0YS97cGFyZW50PXByb2plY3RzLyovbG9jYXRpb25zLyov",
            "Y2F0YWxvZ3MvKn0vdXNlckV2ZW50czpwdXJnZToBKspBXgoyZ29vZ2xlLmNs",
            "b3VkLnJldGFpbC52MmJldGEuUHVyZ2VVc2VyRXZlbnRzUmVzcG9uc2USKGdv",
            "b2dsZS5jbG91ZC5yZXRhaWwudjJiZXRhLlB1cmdlTWV0YWRhdGESmwIKEElt",
            "cG9ydFVzZXJFdmVudHMSMy5nb29nbGUuY2xvdWQucmV0YWlsLnYyYmV0YS5J",
            "bXBvcnRVc2VyRXZlbnRzUmVxdWVzdBodLmdvb2dsZS5sb25ncnVubmluZy5P",
            "cGVyYXRpb24isgGC0+STAkkiRC92MmJldGEve3BhcmVudD1wcm9qZWN0cy8q",
            "L2xvY2F0aW9ucy8qL2NhdGFsb2dzLyp9L3VzZXJFdmVudHM6aW1wb3J0OgEq",
            "ykFgCjNnb29nbGUuY2xvdWQucmV0YWlsLnYyYmV0YS5JbXBvcnRVc2VyRXZl",
            "bnRzUmVzcG9uc2USKWdvb2dsZS5jbG91ZC5yZXRhaWwudjJiZXRhLkltcG9y",
            "dE1ldGFkYXRhEu8BChBSZWpvaW5Vc2VyRXZlbnRzEjMuZ29vZ2xlLmNsb3Vk",
            "LnJldGFpbC52MmJldGEuUmVqb2luVXNlckV2ZW50c1JlcXVlc3QaHS5nb29n",
            "bGUubG9uZ3J1bm5pbmcuT3BlcmF0aW9uIoYBgtPkkwJJIkQvdjJiZXRhL3tw",
            "YXJlbnQ9cHJvamVjdHMvKi9sb2NhdGlvbnMvKi9jYXRhbG9ncy8qfS91c2Vy",
            "RXZlbnRzOnJlam9pbjoBKspBNAoYUmVqb2luVXNlckV2ZW50c1Jlc3BvbnNl",
            "EhhSZWpvaW5Vc2VyRXZlbnRzTWV0YWRhdGEaScpBFXJldGFpbC5nb29nbGVh",
            "cGlzLmNvbdJBLmh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL2F1dGgvY2xv",
            "dWQtcGxhdGZvcm1C3gEKHmNvbS5nb29nbGUuY2xvdWQucmV0YWlsLnYyYmV0",
            "YUIVVXNlckV2ZW50U2VydmljZVByb3RvUAFaQGdvb2dsZS5nb2xhbmcub3Jn",
            "L2dlbnByb3RvL2dvb2dsZWFwaXMvY2xvdWQvcmV0YWlsL3YyYmV0YTtyZXRh",
            "aWyiAgZSRVRBSUyqAhpHb29nbGUuQ2xvdWQuUmV0YWlsLlYyQmV0YcoCGkdv",
            "b2dsZVxDbG91ZFxSZXRhaWxcVjJiZXRh6gIdR29vZ2xlOjpDbG91ZDo6UmV0",
            "YWlsOjpWMmJldGFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Google.Api.ClientReflection.Descriptor, global::Google.Api.FieldBehaviorReflection.Descriptor, global::Google.Api.HttpbodyReflection.Descriptor, global::Google.Cloud.Retail.V2Beta.ExportConfigReflection.Descriptor, global::Google.Cloud.Retail.V2Beta.ImportConfigReflection.Descriptor, global::Google.Cloud.Retail.V2Beta.PurgeConfigReflection.Descriptor, global::Google.Cloud.Retail.V2Beta.UserEventReflection.Descriptor, global::Google.LongRunning.OperationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Cloud.Retail.V2Beta.WriteUserEventRequest), global::Google.Cloud.Retail.V2Beta.WriteUserEventRequest.Parser, new[]{ "Parent", "UserEvent" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Cloud.Retail.V2Beta.CollectUserEventRequest), global::Google.Cloud.Retail.V2Beta.CollectUserEventRequest.Parser, new[]{ "Parent", "UserEvent", "Uri", "Ets" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Cloud.Retail.V2Beta.RejoinUserEventsRequest), global::Google.Cloud.Retail.V2Beta.RejoinUserEventsRequest.Parser, new[]{ "Parent", "UserEventRejoinScope" }, null, new[]{ typeof(global::Google.Cloud.Retail.V2Beta.RejoinUserEventsRequest.Types.UserEventRejoinScope) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Cloud.Retail.V2Beta.RejoinUserEventsResponse), global::Google.Cloud.Retail.V2Beta.RejoinUserEventsResponse.Parser, new[]{ "RejoinedUserEventsCount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Cloud.Retail.V2Beta.RejoinUserEventsMetadata), global::Google.Cloud.Retail.V2Beta.RejoinUserEventsMetadata.Parser, null, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Request message for WriteUserEvent method.
  /// </summary>
  public sealed partial class WriteUserEventRequest : pb::IMessage<WriteUserEventRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WriteUserEventRequest> _parser = new pb::MessageParser<WriteUserEventRequest>(() => new WriteUserEventRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<WriteUserEventRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Cloud.Retail.V2Beta.UserEventServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WriteUserEventRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WriteUserEventRequest(WriteUserEventRequest other) : this() {
      parent_ = other.parent_;
      userEvent_ = other.userEvent_ != null ? other.userEvent_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public WriteUserEventRequest Clone() {
      return new WriteUserEventRequest(this);
    }

    /// <summary>Field number for the "parent" field.</summary>
    public const int ParentFieldNumber = 1;
    private string parent_ = "";
    /// <summary>
    /// Required. The parent catalog resource name, such as
    /// `projects/1234/locations/global/catalogs/default_catalog`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Parent {
      get { return parent_; }
      set {
        parent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_event" field.</summary>
    public const int UserEventFieldNumber = 2;
    private global::Google.Cloud.Retail.V2Beta.UserEvent userEvent_;
    /// <summary>
    /// Required. User event to write.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Cloud.Retail.V2Beta.UserEvent UserEvent {
      get { return userEvent_; }
      set {
        userEvent_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as WriteUserEventRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(WriteUserEventRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Parent != other.Parent) return false;
      if (!object.Equals(UserEvent, other.UserEvent)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Parent.Length != 0) hash ^= Parent.GetHashCode();
      if (userEvent_ != null) hash ^= UserEvent.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Parent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Parent);
      }
      if (userEvent_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UserEvent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Parent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Parent);
      }
      if (userEvent_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UserEvent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Parent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Parent);
      }
      if (userEvent_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserEvent);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(WriteUserEventRequest other) {
      if (other == null) {
        return;
      }
      if (other.Parent.Length != 0) {
        Parent = other.Parent;
      }
      if (other.userEvent_ != null) {
        if (userEvent_ == null) {
          UserEvent = new global::Google.Cloud.Retail.V2Beta.UserEvent();
        }
        UserEvent.MergeFrom(other.UserEvent);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Parent = input.ReadString();
            break;
          }
          case 18: {
            if (userEvent_ == null) {
              UserEvent = new global::Google.Cloud.Retail.V2Beta.UserEvent();
            }
            input.ReadMessage(UserEvent);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Parent = input.ReadString();
            break;
          }
          case 18: {
            if (userEvent_ == null) {
              UserEvent = new global::Google.Cloud.Retail.V2Beta.UserEvent();
            }
            input.ReadMessage(UserEvent);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Request message for CollectUserEvent method.
  /// </summary>
  public sealed partial class CollectUserEventRequest : pb::IMessage<CollectUserEventRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CollectUserEventRequest> _parser = new pb::MessageParser<CollectUserEventRequest>(() => new CollectUserEventRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CollectUserEventRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Cloud.Retail.V2Beta.UserEventServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CollectUserEventRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CollectUserEventRequest(CollectUserEventRequest other) : this() {
      parent_ = other.parent_;
      userEvent_ = other.userEvent_;
      uri_ = other.uri_;
      ets_ = other.ets_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CollectUserEventRequest Clone() {
      return new CollectUserEventRequest(this);
    }

    /// <summary>Field number for the "parent" field.</summary>
    public const int ParentFieldNumber = 1;
    private string parent_ = "";
    /// <summary>
    /// Required. The parent catalog name, such as
    /// `projects/1234/locations/global/catalogs/default_catalog`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Parent {
      get { return parent_; }
      set {
        parent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_event" field.</summary>
    public const int UserEventFieldNumber = 2;
    private string userEvent_ = "";
    /// <summary>
    /// Required. URL encoded UserEvent proto with a length limit of 2,000,000
    /// characters.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UserEvent {
      get { return userEvent_; }
      set {
        userEvent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "uri" field.</summary>
    public const int UriFieldNumber = 3;
    private string uri_ = "";
    /// <summary>
    /// The URL including cgi-parameters but excluding the hash fragment with a
    /// length limit of 5,000 characters. This is often more useful than the
    /// referer URL, because many browsers only send the domain for 3rd party
    /// requests.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Uri {
      get { return uri_; }
      set {
        uri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ets" field.</summary>
    public const int EtsFieldNumber = 4;
    private long ets_;
    /// <summary>
    /// The event timestamp in milliseconds. This prevents browser caching of
    /// otherwise identical get requests. The name is abbreviated to reduce the
    /// payload bytes.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Ets {
      get { return ets_; }
      set {
        ets_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CollectUserEventRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CollectUserEventRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Parent != other.Parent) return false;
      if (UserEvent != other.UserEvent) return false;
      if (Uri != other.Uri) return false;
      if (Ets != other.Ets) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Parent.Length != 0) hash ^= Parent.GetHashCode();
      if (UserEvent.Length != 0) hash ^= UserEvent.GetHashCode();
      if (Uri.Length != 0) hash ^= Uri.GetHashCode();
      if (Ets != 0L) hash ^= Ets.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Parent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Parent);
      }
      if (UserEvent.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserEvent);
      }
      if (Uri.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Uri);
      }
      if (Ets != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Ets);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Parent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Parent);
      }
      if (UserEvent.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserEvent);
      }
      if (Uri.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Uri);
      }
      if (Ets != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Ets);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Parent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Parent);
      }
      if (UserEvent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserEvent);
      }
      if (Uri.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uri);
      }
      if (Ets != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Ets);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CollectUserEventRequest other) {
      if (other == null) {
        return;
      }
      if (other.Parent.Length != 0) {
        Parent = other.Parent;
      }
      if (other.UserEvent.Length != 0) {
        UserEvent = other.UserEvent;
      }
      if (other.Uri.Length != 0) {
        Uri = other.Uri;
      }
      if (other.Ets != 0L) {
        Ets = other.Ets;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Parent = input.ReadString();
            break;
          }
          case 18: {
            UserEvent = input.ReadString();
            break;
          }
          case 26: {
            Uri = input.ReadString();
            break;
          }
          case 32: {
            Ets = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Parent = input.ReadString();
            break;
          }
          case 18: {
            UserEvent = input.ReadString();
            break;
          }
          case 26: {
            Uri = input.ReadString();
            break;
          }
          case 32: {
            Ets = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Request message for RejoinUserEvents method.
  /// </summary>
  public sealed partial class RejoinUserEventsRequest : pb::IMessage<RejoinUserEventsRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RejoinUserEventsRequest> _parser = new pb::MessageParser<RejoinUserEventsRequest>(() => new RejoinUserEventsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RejoinUserEventsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Cloud.Retail.V2Beta.UserEventServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RejoinUserEventsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RejoinUserEventsRequest(RejoinUserEventsRequest other) : this() {
      parent_ = other.parent_;
      userEventRejoinScope_ = other.userEventRejoinScope_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RejoinUserEventsRequest Clone() {
      return new RejoinUserEventsRequest(this);
    }

    /// <summary>Field number for the "parent" field.</summary>
    public const int ParentFieldNumber = 1;
    private string parent_ = "";
    /// <summary>
    /// Required. The parent catalog resource name, such as
    /// `projects/1234/locations/global/catalogs/default_catalog`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Parent {
      get { return parent_; }
      set {
        parent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_event_rejoin_scope" field.</summary>
    public const int UserEventRejoinScopeFieldNumber = 2;
    private global::Google.Cloud.Retail.V2Beta.RejoinUserEventsRequest.Types.UserEventRejoinScope userEventRejoinScope_ = global::Google.Cloud.Retail.V2Beta.RejoinUserEventsRequest.Types.UserEventRejoinScope.Unspecified;
    /// <summary>
    /// The type of the user event rejoin to define the scope and range of the user
    /// events to be rejoined with the latest product catalog. Defaults to
    /// USER_EVENT_REJOIN_SCOPE_UNSPECIFIED if this field is not set, or set to an
    /// invalid integer value.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Cloud.Retail.V2Beta.RejoinUserEventsRequest.Types.UserEventRejoinScope UserEventRejoinScope {
      get { return userEventRejoinScope_; }
      set {
        userEventRejoinScope_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RejoinUserEventsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RejoinUserEventsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Parent != other.Parent) return false;
      if (UserEventRejoinScope != other.UserEventRejoinScope) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Parent.Length != 0) hash ^= Parent.GetHashCode();
      if (UserEventRejoinScope != global::Google.Cloud.Retail.V2Beta.RejoinUserEventsRequest.Types.UserEventRejoinScope.Unspecified) hash ^= UserEventRejoinScope.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Parent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Parent);
      }
      if (UserEventRejoinScope != global::Google.Cloud.Retail.V2Beta.RejoinUserEventsRequest.Types.UserEventRejoinScope.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) UserEventRejoinScope);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Parent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Parent);
      }
      if (UserEventRejoinScope != global::Google.Cloud.Retail.V2Beta.RejoinUserEventsRequest.Types.UserEventRejoinScope.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) UserEventRejoinScope);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Parent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Parent);
      }
      if (UserEventRejoinScope != global::Google.Cloud.Retail.V2Beta.RejoinUserEventsRequest.Types.UserEventRejoinScope.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UserEventRejoinScope);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RejoinUserEventsRequest other) {
      if (other == null) {
        return;
      }
      if (other.Parent.Length != 0) {
        Parent = other.Parent;
      }
      if (other.UserEventRejoinScope != global::Google.Cloud.Retail.V2Beta.RejoinUserEventsRequest.Types.UserEventRejoinScope.Unspecified) {
        UserEventRejoinScope = other.UserEventRejoinScope;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Parent = input.ReadString();
            break;
          }
          case 16: {
            UserEventRejoinScope = (global::Google.Cloud.Retail.V2Beta.RejoinUserEventsRequest.Types.UserEventRejoinScope) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Parent = input.ReadString();
            break;
          }
          case 16: {
            UserEventRejoinScope = (global::Google.Cloud.Retail.V2Beta.RejoinUserEventsRequest.Types.UserEventRejoinScope) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the RejoinUserEventsRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      /// The scope of user events to be rejoined with the latest product catalog.
      /// If the rejoining aims at reducing number of unjoined events, set
      /// UserEventRejoinScope to UNJOINED_EVENTS.
      /// If the rejoining aims at correcting product catalog information in joined
      /// events, set UserEventRejoinScope to JOINED_EVENTS.
      /// If all events needs to be rejoined, set UserEventRejoinScope to
      /// USER_EVENT_REJOIN_SCOPE_UNSPECIFIED.
      /// </summary>
      public enum UserEventRejoinScope {
        /// <summary>
        /// Rejoin all events with the latest product catalog, including both joined
        /// events and unjoined events.
        /// </summary>
        [pbr::OriginalName("USER_EVENT_REJOIN_SCOPE_UNSPECIFIED")] Unspecified = 0,
        /// <summary>
        /// Only rejoin joined events with the latest product catalog.
        /// </summary>
        [pbr::OriginalName("JOINED_EVENTS")] JoinedEvents = 1,
        /// <summary>
        /// Only rejoin unjoined events with the latest product catalog.
        /// </summary>
        [pbr::OriginalName("UNJOINED_EVENTS")] UnjoinedEvents = 2,
      }

    }
    #endregion

  }

  /// <summary>
  /// Response message for RejoinUserEvents method.
  /// </summary>
  public sealed partial class RejoinUserEventsResponse : pb::IMessage<RejoinUserEventsResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RejoinUserEventsResponse> _parser = new pb::MessageParser<RejoinUserEventsResponse>(() => new RejoinUserEventsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RejoinUserEventsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Cloud.Retail.V2Beta.UserEventServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RejoinUserEventsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RejoinUserEventsResponse(RejoinUserEventsResponse other) : this() {
      rejoinedUserEventsCount_ = other.rejoinedUserEventsCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RejoinUserEventsResponse Clone() {
      return new RejoinUserEventsResponse(this);
    }

    /// <summary>Field number for the "rejoined_user_events_count" field.</summary>
    public const int RejoinedUserEventsCountFieldNumber = 1;
    private long rejoinedUserEventsCount_;
    /// <summary>
    /// Number of user events that were joined with latest product catalog.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long RejoinedUserEventsCount {
      get { return rejoinedUserEventsCount_; }
      set {
        rejoinedUserEventsCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RejoinUserEventsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RejoinUserEventsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RejoinedUserEventsCount != other.RejoinedUserEventsCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RejoinedUserEventsCount != 0L) hash ^= RejoinedUserEventsCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RejoinedUserEventsCount != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(RejoinedUserEventsCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RejoinedUserEventsCount != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(RejoinedUserEventsCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RejoinedUserEventsCount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RejoinedUserEventsCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RejoinUserEventsResponse other) {
      if (other == null) {
        return;
      }
      if (other.RejoinedUserEventsCount != 0L) {
        RejoinedUserEventsCount = other.RejoinedUserEventsCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RejoinedUserEventsCount = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RejoinedUserEventsCount = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Metadata for RejoinUserEvents method.
  /// </summary>
  public sealed partial class RejoinUserEventsMetadata : pb::IMessage<RejoinUserEventsMetadata>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RejoinUserEventsMetadata> _parser = new pb::MessageParser<RejoinUserEventsMetadata>(() => new RejoinUserEventsMetadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RejoinUserEventsMetadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Cloud.Retail.V2Beta.UserEventServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RejoinUserEventsMetadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RejoinUserEventsMetadata(RejoinUserEventsMetadata other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RejoinUserEventsMetadata Clone() {
      return new RejoinUserEventsMetadata(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RejoinUserEventsMetadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RejoinUserEventsMetadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RejoinUserEventsMetadata other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
