<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/osconfig/v1alpha/config_common.proto

namespace Google\Cloud\OsConfig\V1alpha;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\OsConfig\V1alpha\OSPolicyResourceCompliance\ExecResourceOutput instead.
     * @deprecated
     */
    class OSPolicyResourceCompliance_ExecResourceOutput {}
}
class_exists(OSPolicyResourceCompliance\ExecResourceOutput::class);
@trigger_error('Google\Cloud\OsConfig\V1alpha\OSPolicyResourceCompliance_ExecResourceOutput is deprecated and will be removed in the next major release. Use Google\Cloud\OsConfig\V1alpha\OSPolicyResourceCompliance\ExecResourceOutput instead', E_USER_DEPRECATED);

