<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/osconfig/v1alpha/os_policy_assignments.proto

namespace Google\Cloud\OsConfig\V1alpha;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\OsConfig\V1alpha\OSPolicyAssignment\LabelSet instead.
     * @deprecated
     */
    class OSPolicyAssignment_LabelSet {}
}
class_exists(OSPolicyAssignment\LabelSet::class);
@trigger_error('Google\Cloud\OsConfig\V1alpha\OSPolicyAssignment_LabelSet is deprecated and will be removed in the next major release. Use Google\Cloud\OsConfig\V1alpha\OSPolicyAssignment\LabelSet instead', E_USER_DEPRECATED);

