# frozen_string_literal: true

# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V8
        module Services
          # Request message for {::Google::Ads::GoogleAds::V8::Services::ReachPlanService::Client#list_plannable_locations ReachPlanService.ListPlannableLocations}.
          class ListPlannableLocationsRequest
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # The list of plannable locations.
          # @!attribute [rw] plannable_locations
          #   @return [::Array<::Google::Ads::GoogleAds::V8::Services::PlannableLocation>]
          #     The list of locations available for planning (Countries, DMAs,
          #     sub-countries).
          #     For locations like Countries and DMAs see
          #     https://developers.google.com/google-ads/api/reference/data/geotargets for
          #     more information.
          class ListPlannableLocationsResponse
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # A plannable location: a country, a DMA, a metro region, a tv region,
          # a province.
          # @!attribute [rw] id
          #   @return [::String]
          #     The location identifier.
          # @!attribute [rw] name
          #   @return [::String]
          #     The unique location name in english.
          # @!attribute [rw] parent_country_id
          #   @return [::Integer]
          #     The parent country code, not present if location is a country.
          #     If present will always be a criterion id: additional information, such as
          #     country name are returned both via ListPlannableLocations or directly by
          #     accessing GeoTargetConstantService with the criterion id.
          class PlannableLocation
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Request to list available products in a given location.
          # @!attribute [rw] plannable_location_id
          #   @return [::String]
          #     Required. The ID of the selected location for planning. To list the available
          #     plannable location ids use ListPlannableLocations.
          class ListPlannableProductsRequest
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # A response with all available products.
          # @!attribute [rw] product_metadata
          #   @return [::Array<::Google::Ads::GoogleAds::V8::Services::ProductMetadata>]
          #     The list of products available for planning and related targeting metadata.
          class ListPlannableProductsResponse
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # The metadata associated with an available plannable product.
          # @!attribute [rw] plannable_product_code
          #   @return [::String]
          #     The code associated with the ad product. E.g. BUMPER, TRUEVIEW_IN_STREAM
          #     To list the available plannable product codes use ListPlannableProducts.
          # @!attribute [rw] plannable_product_name
          #   @return [::String]
          #     The name associated with the ad product.
          # @!attribute [rw] plannable_targeting
          #   @return [::Google::Ads::GoogleAds::V8::Services::PlannableTargeting]
          #     The allowed plannable targeting for this product.
          class ProductMetadata
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # The targeting for which traffic metrics will be reported.
          # @!attribute [rw] age_ranges
          #   @return [::Array<::Google::Ads::GoogleAds::V8::Enums::ReachPlanAgeRangeEnum::ReachPlanAgeRange>]
          #     Allowed plannable age ranges for the product for which metrics will be
          #     reported. Actual targeting is computed by mapping this age range onto
          #     standard Google common.AgeRangeInfo values.
          # @!attribute [rw] genders
          #   @return [::Array<::Google::Ads::GoogleAds::V8::Common::GenderInfo>]
          #     Targetable genders for the ad product.
          # @!attribute [rw] devices
          #   @return [::Array<::Google::Ads::GoogleAds::V8::Common::DeviceInfo>]
          #     Targetable devices for the ad product.
          # @!attribute [rw] networks
          #   @return [::Array<::Google::Ads::GoogleAds::V8::Enums::ReachPlanNetworkEnum::ReachPlanNetwork>]
          #     Targetable networks for the ad product.
          class PlannableTargeting
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Request message for {::Google::Ads::GoogleAds::V8::Services::ReachPlanService::Client#generate_product_mix_ideas ReachPlanService.GenerateProductMixIdeas}.
          # @!attribute [rw] customer_id
          #   @return [::String]
          #     Required. The ID of the customer.
          # @!attribute [rw] plannable_location_id
          #   @return [::String]
          #     Required. The ID of the location, this is one of the ids returned by
          #     ListPlannableLocations.
          # @!attribute [rw] currency_code
          #   @return [::String]
          #     Required. Currency code.
          #     Three-character ISO 4217 currency code.
          # @!attribute [rw] budget_micros
          #   @return [::Integer]
          #     Required. Total budget.
          #     Amount in micros. One million is equivalent to one unit.
          # @!attribute [rw] preferences
          #   @return [::Google::Ads::GoogleAds::V8::Services::Preferences]
          #     The preferences of the suggested product mix.
          #     An unset preference is interpreted as all possible values are allowed,
          #     unless explicitly specified.
          class GenerateProductMixIdeasRequest
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Set of preferences about the planned mix.
          # @!attribute [rw] is_skippable
          #   @return [::Boolean]
          #     True if ad skippable.
          #     If not set, default is any value.
          # @!attribute [rw] starts_with_sound
          #   @return [::Boolean]
          #     True if ad start with sound.
          #     If not set, default is any value.
          # @!attribute [rw] ad_length
          #   @return [::Google::Ads::GoogleAds::V8::Enums::ReachPlanAdLengthEnum::ReachPlanAdLength]
          #     The length of the ad.
          #     If not set, default is any value.
          # @!attribute [rw] top_content_only
          #   @return [::Boolean]
          #     True if ad will only show on the top content.
          #     If not set, default is false.
          # @!attribute [rw] has_guaranteed_price
          #   @return [::Boolean]
          #     True if the price guaranteed. The cost of serving the ad is agreed upfront
          #     and not subject to an auction.
          #     If not set, default is any value.
          class Preferences
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # The suggested product mix.
          # @!attribute [rw] product_allocation
          #   @return [::Array<::Google::Ads::GoogleAds::V8::Services::ProductAllocation>]
          #     A list of products (ad formats) and the associated budget allocation idea.
          class GenerateProductMixIdeasResponse
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # An allocation of a part of the budget on a given product.
          # @!attribute [rw] plannable_product_code
          #   @return [::String]
          #     Selected product for planning. The product codes returned are within the
          #     set of the ones returned by ListPlannableProducts when using the same
          #     location id.
          # @!attribute [rw] budget_micros
          #   @return [::Integer]
          #     The value to be allocated for the suggested product in requested currency.
          #     Amount in micros. One million is equivalent to one unit.
          class ProductAllocation
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Request message for {::Google::Ads::GoogleAds::V8::Services::ReachPlanService::Client#generate_reach_forecast ReachPlanService.GenerateReachForecast}.
          # @!attribute [rw] customer_id
          #   @return [::String]
          #     Required. The ID of the customer.
          # @!attribute [rw] currency_code
          #   @return [::String]
          #     The currency code.
          #     Three-character ISO 4217 currency code.
          # @!attribute [rw] campaign_duration
          #   @return [::Google::Ads::GoogleAds::V8::Services::CampaignDuration]
          #     Required. Campaign duration.
          # @!attribute [rw] cookie_frequency_cap
          #   @return [::Integer]
          #     Desired cookie frequency cap that will be applied to each planned product.
          #     This is equivalent to the frequency cap exposed in Google Ads when creating
          #     a campaign, it represents the maximum number of times an ad can be shown to
          #     the same user.
          #     If not specified no cap is applied.
          #
          #     This field is deprecated in v4 and will eventually be removed.
          #     Please use cookie_frequency_cap_setting instead.
          # @!attribute [rw] cookie_frequency_cap_setting
          #   @return [::Google::Ads::GoogleAds::V8::Services::FrequencyCap]
          #     Desired cookie frequency cap that will be applied to each planned product.
          #     This is equivalent to the frequency cap exposed in Google Ads when creating
          #     a campaign, it represents the maximum number of times an ad can be shown to
          #     the same user during a specified time interval.
          #     If not specified, no cap is applied.
          #
          #     This field replaces the deprecated cookie_frequency_cap field.
          # @!attribute [rw] min_effective_frequency
          #   @return [::Integer]
          #     Desired minimum effective frequency (the number of times a person was
          #     exposed to the ad) for the reported reach metrics [1-10].
          #     This won't affect the targeting, but just the reporting.
          #     If not specified, a default of 1 is applied.
          # @!attribute [rw] targeting
          #   @return [::Google::Ads::GoogleAds::V8::Services::Targeting]
          #     The targeting to be applied to all products selected in the product mix.
          #
          #     This is planned targeting: execution details might vary based on the
          #     advertising product, please consult an implementation specialist.
          #
          #     See specific metrics for details on how targeting affects them.
          # @!attribute [rw] planned_products
          #   @return [::Array<::Google::Ads::GoogleAds::V8::Services::PlannedProduct>]
          #     Required. The products to be forecast.
          #     The max number of allowed planned products is 15.
          class GenerateReachForecastRequest
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # A rule specifying the maximum number of times an ad can be shown to a user
          # over a particular time period.
          # @!attribute [rw] impressions
          #   @return [::Integer]
          #     Required. The number of impressions, inclusive.
          # @!attribute [rw] time_unit
          #   @return [::Google::Ads::GoogleAds::V8::Enums::FrequencyCapTimeUnitEnum::FrequencyCapTimeUnit]
          #     Required. The type of time unit.
          class FrequencyCap
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # The targeting for which traffic metrics will be reported.
          # @!attribute [rw] plannable_location_id
          #   @return [::String]
          #     Required. The ID of the selected location.
          #     Plannable locations ID can be obtained from ListPlannableLocations.
          # @!attribute [rw] age_range
          #   @return [::Google::Ads::GoogleAds::V8::Enums::ReachPlanAgeRangeEnum::ReachPlanAgeRange]
          #     Targeted age range.
          #     If not specified, targets all age ranges.
          # @!attribute [rw] genders
          #   @return [::Array<::Google::Ads::GoogleAds::V8::Common::GenderInfo>]
          #     Targeted genders.
          #     If not specified, targets all genders.
          # @!attribute [rw] devices
          #   @return [::Array<::Google::Ads::GoogleAds::V8::Common::DeviceInfo>]
          #     Targeted devices.
          #     If not specified, targets all applicable devices. Applicable devices vary
          #     by product and region and can be obtained from ListPlannableProducts.
          # @!attribute [rw] network
          #   @return [::Google::Ads::GoogleAds::V8::Enums::ReachPlanNetworkEnum::ReachPlanNetwork]
          #     Targetable network for the ad product.
          #     If not specified, targets all applicable networks. Applicable networks vary
          #     by product and region and can be obtained from ListPlannableProducts.
          class Targeting
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # The duration of a planned campaign.
          # @!attribute [rw] duration_in_days
          #   @return [::Integer]
          #     The duration value in days.
          class CampaignDuration
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # A product being planned for reach.
          # @!attribute [rw] plannable_product_code
          #   @return [::String]
          #     Required. Selected product for planning.
          #     The code associated with the ad product. E.g. Trueview, Bumper
          #     To list the available plannable product codes use ListPlannableProducts.
          # @!attribute [rw] budget_micros
          #   @return [::Integer]
          #     Required. Maximum budget allocation in micros for the selected product.
          #     The value is specified in the selected planning currency_code.
          #     E.g. 1 000 000$ = 1 000 000 000 000 micros.
          class PlannedProduct
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Response message containing the generated reach curve.
          # @!attribute [rw] on_target_audience_metrics
          #   @return [::Google::Ads::GoogleAds::V8::Services::OnTargetAudienceMetrics]
          #     Reference on target audiences for this curve.
          # @!attribute [rw] reach_curve
          #   @return [::Google::Ads::GoogleAds::V8::Services::ReachCurve]
          #     The generated reach curve for the planned product mix.
          class GenerateReachForecastResponse
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # The reach curve for the planned products.
          # @!attribute [rw] reach_forecasts
          #   @return [::Array<::Google::Ads::GoogleAds::V8::Services::ReachForecast>]
          #     All points on the reach curve.
          class ReachCurve
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # A point on reach curve.
          # @!attribute [rw] cost_micros
          #   @return [::Integer]
          #     The cost in micros.
          # @!attribute [rw] forecast
          #   @return [::Google::Ads::GoogleAds::V8::Services::Forecast]
          #     Forecasted traffic metrics for this point.
          # @!attribute [rw] planned_product_reach_forecasts
          #   @return [::Array<::Google::Ads::GoogleAds::V8::Services::PlannedProductReachForecast>]
          #     The forecasted allocation and traffic metrics for each planned product
          #     at this point on the reach curve.
          class ReachForecast
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Forecasted traffic metrics for the planned products and targeting.
          # @!attribute [rw] on_target_reach
          #   @return [::Integer]
          #     Number of unique people reached at least
          #     GenerateReachForecastRequest.min_effective_frequency times that exactly
          #     matches the Targeting.
          # @!attribute [rw] total_reach
          #   @return [::Integer]
          #     Total number of unique people reached at least
          #     GenerateReachForecastRequest.min_effective_frequency times. This includes
          #     people that may fall outside the specified Targeting.
          # @!attribute [rw] on_target_impressions
          #   @return [::Integer]
          #     Number of ad impressions that exactly matches the Targeting.
          # @!attribute [rw] total_impressions
          #   @return [::Integer]
          #     Total number of ad impressions. This includes impressions that may fall
          #     outside the specified Targeting, due to insufficient information on
          #     signed-in users.
          # @!attribute [rw] viewable_impressions
          #   @return [::Integer]
          #     Number of times the ad's impressions were considered viewable.
          #     See https://support.google.com/google-ads/answer/7029393 for
          #     more information about what makes an ad viewable and how
          #     viewability is measured.
          class Forecast
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # The forecasted allocation and traffic metrics for a specific product
          # at a point on the reach curve.
          # @!attribute [rw] plannable_product_code
          #   @return [::String]
          #     Selected product for planning. The product codes returned are within the
          #     set of the ones returned by ListPlannableProducts when using the same
          #     location id.
          # @!attribute [rw] cost_micros
          #   @return [::Integer]
          #     The cost in micros. This may differ from the product's input allocation
          #     if one or more planned products cannot fulfill the budget because of
          #     limited inventory.
          # @!attribute [rw] planned_product_forecast
          #   @return [::Google::Ads::GoogleAds::V8::Services::PlannedProductForecast]
          #     Forecasted traffic metrics for this product.
          class PlannedProductReachForecast
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Forecasted traffic metrics for a planned product.
          # @!attribute [rw] on_target_reach
          #   @return [::Integer]
          #     Number of unique people reached that exactly matches the Targeting.
          # @!attribute [rw] total_reach
          #   @return [::Integer]
          #     Number of unique people reached. This includes people that may fall
          #     outside the specified Targeting.
          # @!attribute [rw] on_target_impressions
          #   @return [::Integer]
          #     Number of ad impressions that exactly matches the Targeting.
          # @!attribute [rw] total_impressions
          #   @return [::Integer]
          #     Total number of ad impressions. This includes impressions that may fall
          #     outside the specified Targeting, due to insufficient information on
          #     signed-in users.
          # @!attribute [rw] viewable_impressions
          #   @return [::Integer]
          #     Number of times the ad's impressions were considered viewable.
          #     See https://support.google.com/google-ads/answer/7029393 for
          #     more information about what makes an ad viewable and how
          #     viewability is measured.
          class PlannedProductForecast
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Audience metrics for the planned products.
          # These metrics consider the following targeting dimensions:
          #
          # - Location
          # - PlannableAgeRange
          # - Gender
          # @!attribute [rw] youtube_audience_size
          #   @return [::Integer]
          #     Reference audience size matching the considered targeting for YouTube.
          # @!attribute [rw] census_audience_size
          #   @return [::Integer]
          #     Reference audience size matching the considered targeting for Census.
          class OnTargetAudienceMetrics
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end
        end
      end
    end
  end
end
