# -*- coding: utf-8 -*-
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
from .resources import (
    AdminQuotaPolicy,
    ConsumerQuotaLimit,
    ConsumerQuotaMetric,
    OperationMetadata,
    OverrideInlineSource,
    QuotaBucket,
    QuotaOverride,
    Service,
    ServiceConfig,
    ServiceIdentity,
    QuotaSafetyCheck,
    QuotaView,
    State,
)
from .serviceusage import (
    BatchCreateAdminOverridesResponse,
    BatchCreateConsumerOverridesResponse,
    BatchEnableServicesRequest,
    CreateAdminOverrideRequest,
    CreateAdminQuotaPolicyMetadata,
    CreateConsumerOverrideRequest,
    DeleteAdminOverrideRequest,
    DeleteAdminQuotaPolicyMetadata,
    DeleteConsumerOverrideRequest,
    DisableServiceRequest,
    EnableServiceRequest,
    GenerateServiceIdentityRequest,
    GetConsumerQuotaLimitRequest,
    GetConsumerQuotaMetricRequest,
    GetServiceIdentityMetadata,
    GetServiceIdentityResponse,
    GetServiceRequest,
    ImportAdminOverridesMetadata,
    ImportAdminOverridesRequest,
    ImportAdminOverridesResponse,
    ImportAdminQuotaPoliciesMetadata,
    ImportAdminQuotaPoliciesResponse,
    ImportConsumerOverridesMetadata,
    ImportConsumerOverridesRequest,
    ImportConsumerOverridesResponse,
    ListAdminOverridesRequest,
    ListAdminOverridesResponse,
    ListConsumerOverridesRequest,
    ListConsumerOverridesResponse,
    ListConsumerQuotaMetricsRequest,
    ListConsumerQuotaMetricsResponse,
    ListServicesRequest,
    ListServicesResponse,
    UpdateAdminOverrideRequest,
    UpdateAdminQuotaPolicyMetadata,
    UpdateConsumerOverrideRequest,
)

__all__ = (
    'AdminQuotaPolicy',
    'ConsumerQuotaLimit',
    'ConsumerQuotaMetric',
    'OperationMetadata',
    'OverrideInlineSource',
    'QuotaBucket',
    'QuotaOverride',
    'Service',
    'ServiceConfig',
    'ServiceIdentity',
    'QuotaSafetyCheck',
    'QuotaView',
    'State',
    'BatchCreateAdminOverridesResponse',
    'BatchCreateConsumerOverridesResponse',
    'BatchEnableServicesRequest',
    'CreateAdminOverrideRequest',
    'CreateAdminQuotaPolicyMetadata',
    'CreateConsumerOverrideRequest',
    'DeleteAdminOverrideRequest',
    'DeleteAdminQuotaPolicyMetadata',
    'DeleteConsumerOverrideRequest',
    'DisableServiceRequest',
    'EnableServiceRequest',
    'GenerateServiceIdentityRequest',
    'GetConsumerQuotaLimitRequest',
    'GetConsumerQuotaMetricRequest',
    'GetServiceIdentityMetadata',
    'GetServiceIdentityResponse',
    'GetServiceRequest',
    'ImportAdminOverridesMetadata',
    'ImportAdminOverridesRequest',
    'ImportAdminOverridesResponse',
    'ImportAdminQuotaPoliciesMetadata',
    'ImportAdminQuotaPoliciesResponse',
    'ImportConsumerOverridesMetadata',
    'ImportConsumerOverridesRequest',
    'ImportConsumerOverridesResponse',
    'ListAdminOverridesRequest',
    'ListAdminOverridesResponse',
    'ListConsumerOverridesRequest',
    'ListConsumerOverridesResponse',
    'ListConsumerQuotaMetricsRequest',
    'ListConsumerQuotaMetricsResponse',
    'ListServicesRequest',
    'ListServicesResponse',
    'UpdateAdminOverrideRequest',
    'UpdateAdminQuotaPolicyMetadata',
    'UpdateConsumerOverrideRequest',
)
