<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/bigquery/storage/v1alpha2/storage.proto

namespace Google\Cloud\Bigquery\Storage\V1alpha2;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response message for `BatchCommitWriteStreams`.
 *
 * Generated from protobuf message <code>google.cloud.bigquery.storage.v1alpha2.BatchCommitWriteStreamsResponse</code>
 */
class BatchCommitWriteStreamsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The time at which streams were committed in microseconds granularity.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp commit_time = 1;</code>
     */
    protected $commit_time = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $commit_time
     *           The time at which streams were committed in microseconds granularity.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Bigquery\Storage\V1Alpha2\Storage::initOnce();
        parent::__construct($data);
    }

    /**
     * The time at which streams were committed in microseconds granularity.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp commit_time = 1;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCommitTime()
    {
        return isset($this->commit_time) ? $this->commit_time : null;
    }

    public function hasCommitTime()
    {
        return isset($this->commit_time);
    }

    public function clearCommitTime()
    {
        unset($this->commit_time);
    }

    /**
     * The time at which streams were committed in microseconds granularity.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp commit_time = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCommitTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->commit_time = $var;

        return $this;
    }

}

