<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/videointelligence/v1p3beta1/video_intelligence.proto

namespace Google\Cloud\VideoIntelligence\V1p3beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Celebrity recognition annotation per video.
 *
 * Generated from protobuf message <code>google.cloud.videointelligence.v1p3beta1.CelebrityRecognitionAnnotation</code>
 */
class CelebrityRecognitionAnnotation extends \Google\Protobuf\Internal\Message
{
    /**
     * The tracks detected from the input video, including recognized celebrities
     * and other detected faces in the video.
     *
     * Generated from protobuf field <code>repeated .google.cloud.videointelligence.v1p3beta1.CelebrityTrack celebrity_tracks = 1;</code>
     */
    private $celebrity_tracks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Cloud\VideoIntelligence\V1p3beta1\CelebrityTrack[]|\Google\Protobuf\Internal\RepeatedField $celebrity_tracks
     *           The tracks detected from the input video, including recognized celebrities
     *           and other detected faces in the video.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Videointelligence\V1P3Beta1\VideoIntelligence::initOnce();
        parent::__construct($data);
    }

    /**
     * The tracks detected from the input video, including recognized celebrities
     * and other detected faces in the video.
     *
     * Generated from protobuf field <code>repeated .google.cloud.videointelligence.v1p3beta1.CelebrityTrack celebrity_tracks = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCelebrityTracks()
    {
        return $this->celebrity_tracks;
    }

    /**
     * The tracks detected from the input video, including recognized celebrities
     * and other detected faces in the video.
     *
     * Generated from protobuf field <code>repeated .google.cloud.videointelligence.v1p3beta1.CelebrityTrack celebrity_tracks = 1;</code>
     * @param \Google\Cloud\VideoIntelligence\V1p3beta1\CelebrityTrack[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCelebrityTracks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\VideoIntelligence\V1p3beta1\CelebrityTrack::class);
        $this->celebrity_tracks = $arr;

        return $this;
    }

}

