<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/aiplatform/v1/model_evaluation_slice.proto

namespace GPBMetadata\Google\Cloud\Aiplatform\V1;

class ModelEvaluationSlice
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Api\Resource::initOnce();
        \GPBMetadata\Google\Protobuf\Struct::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            '
§
7google/cloud/aiplatform/v1/model_evaluation_slice.protogoogle.cloud.aiplatform.v1google/api/resource.protogoogle/protobuf/struct.protogoogle/protobuf/timestamp.protogoogle/api/annotations.proto"∆
ModelEvaluationSlice
name (	B‡AJ
slice (26.google.cloud.aiplatform.v1.ModelEvaluationSlice.SliceB‡A
metrics_schema_uri (	B‡A,
metrics (2.google.protobuf.ValueB‡A4
create_time (2.google.protobuf.TimestampB‡A3
Slice
	dimension (	B‡A
value (	B‡A:îÍAê
.aiplatform.googleapis.com/ModelEvaluationSlice^projects/{project}/locations/{location}/models/{model}/evaluations/{evaluation}/slices/{slice}BÉ
com.google.cloud.aiplatform.v1BModelEvaluationSliceProtoPZDgoogle.golang.org/genproto/googleapis/cloud/aiplatform/v1;aiplatformbproto3'
        , true);

        static::$is_initialized = true;
    }
}

