<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/gkehub/v1alpha/service.proto

namespace GPBMetadata\Google\Cloud\Gkehub\V1Alpha;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\Client::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Api\Resource::initOnce();
        \GPBMetadata\Google\Cloud\Gkehub\V1Alpha\Feature::initOnce();
        \GPBMetadata\Google\Longrunning\Operations::initOnce();
        \GPBMetadata\Google\Protobuf\FieldMask::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            '
›
)google/cloud/gkehub/v1alpha/service.protogoogle.cloud.gkehub.v1alphagoogle/api/client.protogoogle/api/field_behavior.protogoogle/api/resource.proto)google/cloud/gkehub/v1alpha/feature.proto#google/longrunning/operations.proto google/protobuf/field_mask.protogoogle/protobuf/timestamp.proto"n
ListFeaturesRequest
parent (	
	page_size (

page_token (	
filter (	
order_by (	"h
ListFeaturesResponse7
	resources (2$.google.cloud.gkehub.v1alpha.Feature
next_page_token (	"!
GetFeatureRequest
name (	"ã
CreateFeatureRequest
parent (	

feature_id (	6
resource (2$.google.cloud.gkehub.v1alpha.Feature

request_id (	B‡A"L
DeleteFeatureRequest
name (	
force (

request_id (	B‡A"¶
UpdateFeatureRequest
name (	/
update_mask (2.google.protobuf.FieldMask6
resource (2$.google.cloud.gkehub.v1alpha.Feature

request_id (	B‡A"˘
OperationMetadata4
create_time (2.google.protobuf.TimestampB‡A1
end_time (2.google.protobuf.TimestampB‡A
target (	B‡A
verb (	B‡A
status_detail (	B‡A
cancel_requested (B‡A
api_version (	B‡A2–
GkeHub∑
ListFeatures0.google.cloud.gkehub.v1alpha.ListFeaturesRequest1.google.cloud.gkehub.v1alpha.ListFeaturesResponse"BÇ”‰ì31/v1alpha/{parent=projects/*/locations/*}/features⁄Aparent§

GetFeature..google.cloud.gkehub.v1alpha.GetFeatureRequest$.google.cloud.gkehub.v1alpha.Feature"@Ç”‰ì31/v1alpha/{name=projects/*/locations/*/features/*}⁄Aname‚
CreateFeature1.google.cloud.gkehub.v1alpha.CreateFeatureRequest.google.longrunning.Operation"Ç”‰ì="1/v1alpha/{parent=projects/*/locations/*}/features:resource⁄Aparent,resource,feature_id A
FeatureOperationMetadata–
DeleteFeature1.google.cloud.gkehub.v1alpha.DeleteFeatureRequest.google.longrunning.Operation"mÇ”‰ì3*1/v1alpha/{name=projects/*/locations/*/features/*}⁄Aname A*
google.protobuf.EmptyOperationMetadata·
UpdateFeature1.google.cloud.gkehub.v1alpha.UpdateFeatureRequest.google.longrunning.Operation"~Ç”‰ì=21/v1alpha/{name=projects/*/locations/*/features/*}:resource⁄Aname,resource,update_mask A
FeatureOperationMetadataI Agkehub.googleapis.com“A.https://www.googleapis.com/auth/cloud-platformB—
com.google.cloud.gkehub.v1alphaBServiceProtoPZAgoogle.golang.org/genproto/googleapis/cloud/gkehub/v1alpha;gkehub™Google.Cloud.GkeHub.V1Alpha Google\\Cloud\\GkeHub\\V1alphaÍGoogle::Cloud::GkeHub::V1alphabproto3'
        , true);

        static::$is_initialized = true;
    }
}

