<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/apps/alertcenter/v1beta1/alertcenter.proto

namespace Google\Apps\AlertCenter\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Update the customer level settings.
 *
 * Generated from protobuf message <code>google.apps.alertcenter.v1beta1.UpdateSettingsRequest</code>
 */
class UpdateSettingsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Optional. The unique identifier of the Google Workspace organization
     * account of the customer the alert settings are associated with.
     * Inferred from the caller identity if not provided.
     *
     * Generated from protobuf field <code>string customer_id = 1;</code>
     */
    protected $customer_id = '';
    /**
     * The customer settings to update.
     *
     * Generated from protobuf field <code>.google.apps.alertcenter.v1beta1.Settings settings = 2;</code>
     */
    protected $settings = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $customer_id
     *           Optional. The unique identifier of the Google Workspace organization
     *           account of the customer the alert settings are associated with.
     *           Inferred from the caller identity if not provided.
     *     @type \Google\Apps\AlertCenter\V1beta1\Settings $settings
     *           The customer settings to update.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Apps\Alertcenter\V1Beta1\Alertcenter::initOnce();
        parent::__construct($data);
    }

    /**
     * Optional. The unique identifier of the Google Workspace organization
     * account of the customer the alert settings are associated with.
     * Inferred from the caller identity if not provided.
     *
     * Generated from protobuf field <code>string customer_id = 1;</code>
     * @return string
     */
    public function getCustomerId()
    {
        return $this->customer_id;
    }

    /**
     * Optional. The unique identifier of the Google Workspace organization
     * account of the customer the alert settings are associated with.
     * Inferred from the caller identity if not provided.
     *
     * Generated from protobuf field <code>string customer_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_id = $var;

        return $this;
    }

    /**
     * The customer settings to update.
     *
     * Generated from protobuf field <code>.google.apps.alertcenter.v1beta1.Settings settings = 2;</code>
     * @return \Google\Apps\AlertCenter\V1beta1\Settings|null
     */
    public function getSettings()
    {
        return isset($this->settings) ? $this->settings : null;
    }

    public function hasSettings()
    {
        return isset($this->settings);
    }

    public function clearSettings()
    {
        unset($this->settings);
    }

    /**
     * The customer settings to update.
     *
     * Generated from protobuf field <code>.google.apps.alertcenter.v1beta1.Settings settings = 2;</code>
     * @param \Google\Apps\AlertCenter\V1beta1\Settings $var
     * @return $this
     */
    public function setSettings($var)
    {
        GPBUtil::checkMessage($var, \Google\Apps\AlertCenter\V1beta1\Settings::class);
        $this->settings = $var;

        return $this;
    }

}

