<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/retail/v2beta/product.proto

namespace Google\Cloud\Retail\V2beta;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Retail\V2beta\Product\Availability instead.
     * @deprecated
     */
    class Product_Availability {}
}
class_exists(Product\Availability::class);
@trigger_error('Google\Cloud\Retail\V2beta\Product_Availability is deprecated and will be removed in the next major release. Use Google\Cloud\Retail\V2beta\Product\Availability instead', E_USER_DEPRECATED);

