# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/websecurityscanner/v1alpha/finding_addon.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("google/cloud/websecurityscanner/v1alpha/finding_addon.proto", :syntax => :proto3) do
    add_message "google.cloud.websecurityscanner.v1alpha.OutdatedLibrary" do
      optional :library_name, :string, 1
      optional :version, :string, 2
      repeated :learn_more_urls, :string, 3
    end
    add_message "google.cloud.websecurityscanner.v1alpha.ViolatingResource" do
      optional :content_type, :string, 1
      optional :resource_url, :string, 2
    end
    add_message "google.cloud.websecurityscanner.v1alpha.VulnerableParameters" do
      repeated :parameter_names, :string, 1
    end
    add_message "google.cloud.websecurityscanner.v1alpha.VulnerableHeaders" do
      repeated :headers, :message, 1, "google.cloud.websecurityscanner.v1alpha.VulnerableHeaders.Header"
      repeated :missing_headers, :message, 2, "google.cloud.websecurityscanner.v1alpha.VulnerableHeaders.Header"
    end
    add_message "google.cloud.websecurityscanner.v1alpha.VulnerableHeaders.Header" do
      optional :name, :string, 1
      optional :value, :string, 2
    end
    add_message "google.cloud.websecurityscanner.v1alpha.Xss" do
      repeated :stack_traces, :string, 1
      optional :error_message, :string, 2
    end
  end
end

module Google
  module Cloud
    module Websecurityscanner
      module V1alpha
        OutdatedLibrary = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.websecurityscanner.v1alpha.OutdatedLibrary").msgclass
        ViolatingResource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.websecurityscanner.v1alpha.ViolatingResource").msgclass
        VulnerableParameters = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.websecurityscanner.v1alpha.VulnerableParameters").msgclass
        VulnerableHeaders = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.websecurityscanner.v1alpha.VulnerableHeaders").msgclass
        VulnerableHeaders::Header = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.websecurityscanner.v1alpha.VulnerableHeaders.Header").msgclass
        Xss = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.cloud.websecurityscanner.v1alpha.Xss").msgclass
      end
    end
  end
end
