<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/bigquery/storage/v1beta2/arrow.proto

namespace Google\Cloud\Bigquery\Storage\V1beta2\ArrowSerializationOptions;

use UnexpectedValueException;

/**
 * The IPC format to use when serializing Arrow streams.
 *
 * Protobuf type <code>google.cloud.bigquery.storage.v1beta2.ArrowSerializationOptions.Format</code>
 */
class Format
{
    /**
     * If unspecied the IPC format as of 0.15 release will be used.
     *
     * Generated from protobuf enum <code>FORMAT_UNSPECIFIED = 0;</code>
     */
    const FORMAT_UNSPECIFIED = 0;
    /**
     * Use the legacy IPC message format as of Apache Arrow Release 0.14.
     *
     * Generated from protobuf enum <code>ARROW_0_14 = 1;</code>
     */
    const ARROW_0_14 = 1;
    /**
     * Use the message format as of Apache Arrow Release 0.15.
     *
     * Generated from protobuf enum <code>ARROW_0_15 = 2;</code>
     */
    const ARROW_0_15 = 2;

    private static $valueToName = [
        self::FORMAT_UNSPECIFIED => 'FORMAT_UNSPECIFIED',
        self::ARROW_0_14 => 'ARROW_0_14',
        self::ARROW_0_15 => 'ARROW_0_15',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Format::class, \Google\Cloud\Bigquery\Storage\V1beta2\ArrowSerializationOptions_Format::class);

