<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/datacatalog/v1beta1/schema.proto

namespace GPBMetadata\Google\Cloud\Datacatalog\V1Beta1;

class Schema
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        $pool->internalAddGeneratedFile(
            '
ø
-google/cloud/datacatalog/v1beta1/schema.proto google.cloud.datacatalog.v1beta1"N
SchemaD
columns (2..google.cloud.datacatalog.v1beta1.ColumnSchemaB‡A"¨
ColumnSchema
column (	B‡A
type (	B‡A
description (	B‡A
mode (	B‡AG

subcolumns (2..google.cloud.datacatalog.v1beta1.ColumnSchemaB‡AB‰
$com.google.cloud.datacatalog.v1beta1PZKgoogle.golang.org/genproto/googleapis/cloud/datacatalog/v1beta1;datacatalog¯™ Google.Cloud.DataCatalog.V1Beta1  Google\\Cloud\\DataCatalog\\V1beta1Í#Google::Cloud::DataCatalog::V1beta1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

