# frozen_string_literal: true

# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Cloud
    module Sql
      module V1
        # Instance add server CA request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL instance ID. This does not include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     Project ID of the project that contains the instance.
        class SqlInstancesAddServerCaRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance clone request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     The ID of the Cloud SQL instance to be cloned (source). This does not
        #     include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     Project ID of the source as well as the clone Cloud SQL instance.
        # @!attribute [rw] body
        #   @return [::Google::Cloud::Sql::V1::InstancesCloneRequest]
        class SqlInstancesCloneRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance delete request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL instance ID. This does not include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     Project ID of the project that contains the instance to be deleted.
        class SqlInstancesDeleteRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance demote master request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL instance name.
        # @!attribute [rw] project
        #   @return [::String]
        #     ID of the project that contains the instance.
        # @!attribute [rw] body
        #   @return [::Google::Cloud::Sql::V1::InstancesDemoteMasterRequest]
        class SqlInstancesDemoteMasterRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance export request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL instance ID. This does not include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     Project ID of the project that contains the instance to be exported.
        # @!attribute [rw] body
        #   @return [::Google::Cloud::Sql::V1::InstancesExportRequest]
        class SqlInstancesExportRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance failover request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL instance ID. This does not include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     ID of the project that contains the read replica.
        # @!attribute [rw] body
        #   @return [::Google::Cloud::Sql::V1::InstancesFailoverRequest]
        class SqlInstancesFailoverRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance get request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Database instance ID. This does not include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     Project ID of the project that contains the instance.
        class SqlInstancesGetRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance import request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL instance ID. This does not include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     Project ID of the project that contains the instance.
        # @!attribute [rw] body
        #   @return [::Google::Cloud::Sql::V1::InstancesImportRequest]
        class SqlInstancesImportRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance insert request.
        # @!attribute [rw] project
        #   @return [::String]
        #     Project ID of the project to which the newly created Cloud SQL instances
        #     should belong.
        # @!attribute [rw] body
        #   @return [::Google::Cloud::Sql::V1::DatabaseInstance]
        class SqlInstancesInsertRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance list request.
        # @!attribute [rw] filter
        #   @return [::String]
        #     A filter expression that filters resources listed in the response.
        #     The expression is in the form of field:value. For example,
        #     'instanceType:CLOUD_SQL_INSTANCE'. Fields can be nested as needed as per
        #     their JSON representation, such as 'settings.userLabels.auto_start:true'.
        #
        #     Multiple filter queries are space-separated. For example.
        #     'state:RUNNABLE instanceType:CLOUD_SQL_INSTANCE'. By default, each
        #     expression is an AND expression. However, you can include AND and OR
        #     expressions explicitly.
        # @!attribute [rw] max_results
        #   @return [::Integer]
        #     The maximum number of results to return per response.
        # @!attribute [rw] page_token
        #   @return [::String]
        #     A previously-returned page token representing part of the larger set of
        #     results to view.
        # @!attribute [rw] project
        #   @return [::String]
        #     Project ID of the project for which to list Cloud SQL instances.
        class SqlInstancesListRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance list server CAs request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL instance ID. This does not include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     Project ID of the project that contains the instance.
        class SqlInstancesListServerCasRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance patch request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL instance ID. This does not include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     Project ID of the project that contains the instance.
        # @!attribute [rw] body
        #   @return [::Google::Cloud::Sql::V1::DatabaseInstance]
        class SqlInstancesPatchRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance promote replica request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL read replica instance name.
        # @!attribute [rw] project
        #   @return [::String]
        #     ID of the project that contains the read replica.
        class SqlInstancesPromoteReplicaRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance reset SSL config request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL instance ID. This does not include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     Project ID of the project that contains the instance.
        class SqlInstancesResetSslConfigRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance restart request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL instance ID. This does not include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     Project ID of the project that contains the instance to be restarted.
        class SqlInstancesRestartRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance restore backup request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL instance ID. This does not include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     Project ID of the project that contains the instance.
        # @!attribute [rw] body
        #   @return [::Google::Cloud::Sql::V1::InstancesRestoreBackupRequest]
        class SqlInstancesRestoreBackupRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance rotate server CA request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL instance ID. This does not include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     Project ID of the project that contains the instance.
        # @!attribute [rw] body
        #   @return [::Google::Cloud::Sql::V1::InstancesRotateServerCaRequest]
        class SqlInstancesRotateServerCaRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance start replica request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL read replica instance name.
        # @!attribute [rw] project
        #   @return [::String]
        #     ID of the project that contains the read replica.
        class SqlInstancesStartReplicaRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance stop replica request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL read replica instance name.
        # @!attribute [rw] project
        #   @return [::String]
        #     ID of the project that contains the read replica.
        class SqlInstancesStopReplicaRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance truncate log request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL instance ID. This does not include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     Project ID of the Cloud SQL project.
        # @!attribute [rw] body
        #   @return [::Google::Cloud::Sql::V1::InstancesTruncateLogRequest]
        class SqlInstancesTruncateLogRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance update request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL instance ID. This does not include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     Project ID of the project that contains the instance.
        # @!attribute [rw] body
        #   @return [::Google::Cloud::Sql::V1::DatabaseInstance]
        class SqlInstancesUpdateRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance reschedule maintenance request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL instance ID. This does not include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     ID of the project that contains the instance.
        # @!attribute [rw] body
        #   @return [::Google::Cloud::Sql::V1::SqlInstancesRescheduleMaintenanceRequestBody]
        class SqlInstancesRescheduleMaintenanceRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance verify external sync settings request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL instance ID. This does not include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     Project ID of the project that contains the instance.
        # @!attribute [rw] verify_connection_only
        #   @return [::Boolean]
        #     Flag to enable verifying connection only
        # @!attribute [rw] sync_mode
        #   @return [::Google::Cloud::Sql::V1::SqlInstancesVerifyExternalSyncSettingsRequest::ExternalSyncMode]
        #     External sync mode
        # @!attribute [rw] verify_replication_only
        #   @return [::Boolean]
        #     Optional. Flag to verify settings required by replication setup only
        # @!attribute [rw] mysql_sync_config
        #   @return [::Google::Cloud::Sql::V1::MySqlSyncConfig]
        #     Optional. MySQL-specific settings for start external sync.
        class SqlInstancesVerifyExternalSyncSettingsRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods

          module ExternalSyncMode
            # Unknown external sync mode, will be defaulted to ONLINE mode
            EXTERNAL_SYNC_MODE_UNSPECIFIED = 0

            # Online external sync will set up replication after initial data external
            # sync
            ONLINE = 1

            # Offline external sync only dumps and loads a one-time snapshot of
            # the primary instance's data
            OFFLINE = 2
          end
        end

        # Instance start external sync request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL instance ID. This does not include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     ID of the project that contains the instance.
        # @!attribute [rw] sync_mode
        #   @return [::Google::Cloud::Sql::V1::SqlInstancesVerifyExternalSyncSettingsRequest::ExternalSyncMode]
        #     External sync mode.
        # @!attribute [rw] skip_verification
        #   @return [::Boolean]
        #     Whether to skip the verification step (VESS).
        # @!attribute [rw] mysql_sync_config
        #   @return [::Google::Cloud::Sql::V1::MySqlSyncConfig]
        #     MySQL-specific settings for start external sync.
        class SqlInstancesStartExternalSyncRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance create ephemeral certificate request.
        # @!attribute [rw] instance
        #   @return [::String]
        #     Cloud SQL instance ID. This does not include the project ID.
        # @!attribute [rw] project
        #   @return [::String]
        #     Project ID of the Cloud SQL project.
        # @!attribute [rw] body
        #   @return [::Google::Cloud::Sql::V1::SslCertsCreateEphemeralRequest]
        class SqlInstancesCreateEphemeralCertRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Database instance clone request.
        # @!attribute [rw] clone_context
        #   @return [::Google::Cloud::Sql::V1::CloneContext]
        #     Contains details about the clone operation.
        class InstancesCloneRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Database demote primary instance request.
        # @!attribute [rw] demote_master_context
        #   @return [::Google::Cloud::Sql::V1::DemoteMasterContext]
        #     Contains details about the demoteMaster operation.
        class InstancesDemoteMasterRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Database instance export request.
        # @!attribute [rw] export_context
        #   @return [::Google::Cloud::Sql::V1::ExportContext]
        #     Contains details about the export operation.
        class InstancesExportRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance failover request.
        # @!attribute [rw] failover_context
        #   @return [::Google::Cloud::Sql::V1::FailoverContext]
        #     Failover Context.
        class InstancesFailoverRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # SslCerts create ephemeral certificate request.
        # @!attribute [rw] public_key
        #   @return [::String]
        #     PEM encoded public key to include in the signed certificate.
        # @!attribute [rw] access_token
        #   @return [::String]
        #     Access token to include in the signed certificate.
        class SslCertsCreateEphemeralRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Database instance import request.
        # @!attribute [rw] import_context
        #   @return [::Google::Cloud::Sql::V1::ImportContext]
        #     Contains details about the import operation.
        class InstancesImportRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Database instances list response.
        # @!attribute [rw] kind
        #   @return [::String]
        #     This is always **sql#instancesList**.
        # @!attribute [rw] warnings
        #   @return [::Array<::Google::Cloud::Sql::V1::ApiWarning>]
        #     List of warnings that occurred while handling the request.
        # @!attribute [rw] items
        #   @return [::Array<::Google::Cloud::Sql::V1::DatabaseInstance>]
        #     List of database instance resources.
        # @!attribute [rw] next_page_token
        #   @return [::String]
        #     The continuation token, used to page through large result sets. Provide
        #     this value in a subsequent request to return the next page of results.
        class InstancesListResponse
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instances ListServerCas response.
        # @!attribute [rw] certs
        #   @return [::Array<::Google::Cloud::Sql::V1::SslCert>]
        #     List of server CA certificates for the instance.
        # @!attribute [rw] active_version
        #   @return [::String]
        # @!attribute [rw] kind
        #   @return [::String]
        #     This is always **sql#instancesListServerCas**.
        class InstancesListServerCasResponse
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Database instance restore backup request.
        # @!attribute [rw] restore_backup_context
        #   @return [::Google::Cloud::Sql::V1::RestoreBackupContext]
        #     Parameters required to perform the restore backup operation.
        class InstancesRestoreBackupRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Rotate server CA request.
        # @!attribute [rw] rotate_server_ca_context
        #   @return [::Google::Cloud::Sql::V1::RotateServerCaContext]
        #     Contains details about the rotate server CA operation.
        class InstancesRotateServerCaRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance truncate log request.
        # @!attribute [rw] truncate_log_context
        #   @return [::Google::Cloud::Sql::V1::TruncateLogContext]
        #     Contains details about the truncate log operation.
        class InstancesTruncateLogRequest
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance verify external sync settings response.
        # @!attribute [rw] kind
        #   @return [::String]
        #     This is always **sql#migrationSettingErrorList**.
        # @!attribute [rw] errors
        #   @return [::Array<::Google::Cloud::Sql::V1::SqlExternalSyncSettingError>]
        #     List of migration violations.
        # @!attribute [rw] warnings
        #   @return [::Array<::Google::Cloud::Sql::V1::SqlExternalSyncSettingError>]
        #     List of migration warnings.
        class SqlInstancesVerifyExternalSyncSettingsResponse
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Database instance clone context.
        # @!attribute [rw] kind
        #   @return [::String]
        #     This is always **sql#cloneContext**.
        # @!attribute [rw] pitr_timestamp_ms
        #   @return [::Integer]
        #     Reserved for future use.
        # @!attribute [rw] destination_instance_name
        #   @return [::String]
        #     Name of the Cloud SQL instance to be created as a clone.
        # @!attribute [rw] bin_log_coordinates
        #   @return [::Google::Cloud::Sql::V1::BinLogCoordinates]
        #     Binary log coordinates, if specified, identify the position up to which the
        #     source instance is cloned. If not specified, the source instance is
        #     cloned up to the most recent binary log coordinates.
        # @!attribute [rw] point_in_time
        #   @return [::Google::Protobuf::Timestamp]
        #     Timestamp, if specified, identifies the time to which the source instance
        #     is cloned.
        class CloneContext
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Binary log coordinates.
        # @!attribute [rw] bin_log_file_name
        #   @return [::String]
        #     Name of the binary log file for a Cloud SQL instance.
        # @!attribute [rw] bin_log_position
        #   @return [::Integer]
        #     Position (offset) within the binary log file.
        # @!attribute [rw] kind
        #   @return [::String]
        #     This is always **sql#binLogCoordinates**.
        class BinLogCoordinates
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # A Cloud SQL instance resource.
        # @!attribute [rw] kind
        #   @return [::String]
        #     This is always **sql#instance**.
        # @!attribute [rw] state
        #   @return [::Google::Cloud::Sql::V1::DatabaseInstance::SqlInstanceState]
        #     The current serving state of the Cloud SQL instance. This can be one of the
        #     following:
        #     *  **SQL_INSTANCE_STATE_UNSPECIFIED**: The state of the instance is
        #     unknown.
        #     *  **RUNNABLE**: The instance is running, or has been stopped by owner.
        #     *  **SUSPENDED**: The instance is not available, for example due to
        #     problems with billing.
        #     *  **PENDING_DELETE**: The instance is being deleted.
        #     *  **PENDING_CREATE**: The instance is being created.
        #     *  **MAINTENANCE**: The instance is down for maintenance.
        #     *  **FAILED**: The instance creation failed.
        # @!attribute [rw] database_version
        #   @return [::Google::Cloud::Sql::V1::SqlDatabaseVersion]
        #     The database engine type and version. The **databaseVersion** field cannot
        #     be changed after instance creation.
        #     *  **MySQL instances**: MYSQL_8_0, MYSQL_5_7 (default), or MYSQL_5_6.
        #     *  **PostgreSQL instances**: POSTGRES_9_6, POSTGRES_10, POSTGRES_11,
        #     POSTGRES_12, POSTGRES_13 (default).
        #     *  **SQL Server instances**: SQLSERVER_2019_STANDARD,
        #     SQLSERVER_2019_ENTERPRISE, SQLSERVER_2019_EXPRESS, or SQLSERVER_2019_WEB,
        #     SQLSERVER_2017_STANDARD (default), SQLSERVER_2017_ENTERPRISE,
        #     SQLSERVER_2017_EXPRESS, or SQLSERVER_2017_WEB.
        # @!attribute [rw] settings
        #   @return [::Google::Cloud::Sql::V1::Settings]
        #     The user settings.
        # @!attribute [rw] etag
        #   @return [::String]
        #     This field is deprecated and will be removed from a future version of the
        #     API. Use the **settings.settingsVersion** field instead.
        # @!attribute [rw] failover_replica
        #   @return [::Google::Cloud::Sql::V1::DatabaseInstance::SqlFailoverReplica]
        #     The name and status of the failover replica.
        # @!attribute [rw] master_instance_name
        #   @return [::String]
        #     The name of the instance which will act as primary in the replication
        #     setup.
        # @!attribute [rw] replica_names
        #   @return [::Array<::String>]
        #     The replicas of the instance.
        # @!attribute [rw] max_disk_size
        #   @return [::Google::Protobuf::Int64Value]
        #     The maximum disk size of the instance in bytes.
        # @!attribute [rw] current_disk_size
        #   @return [::Google::Protobuf::Int64Value]
        #     The current disk usage of the instance in bytes. This property has been
        #     deprecated. Use the
        #     "cloudsql.googleapis.com/database/disk/bytes_used" metric in Cloud
        #     Monitoring API instead. Please see [this
        #     announcement](https://groups.google.com/d/msg/google-cloud-sql-announce/I_7-F9EBhT0/BtvFtdFeAgAJ)
        #     for details.
        # @!attribute [rw] ip_addresses
        #   @return [::Array<::Google::Cloud::Sql::V1::IpMapping>]
        #     The assigned IP addresses for the instance.
        # @!attribute [rw] server_ca_cert
        #   @return [::Google::Cloud::Sql::V1::SslCert]
        #     SSL configuration.
        # @!attribute [rw] instance_type
        #   @return [::Google::Cloud::Sql::V1::SqlInstanceType]
        #     The instance type. This can be one of the following:
        #     *  **CLOUD_SQL_INSTANCE**: A Cloud SQL instance that is not replicating
        #     from a primary instance.
        #     *  **ON_PREMISES_INSTANCE**: An instance running on the customer's
        #     premises.
        #     *  **READ_REPLICA_INSTANCE**: A Cloud SQL instance configured as a
        #     read-replica.
        # @!attribute [rw] project
        #   @return [::String]
        #     The project ID of the project containing the Cloud SQL instance. The Google
        #     apps domain is prefixed if applicable.
        # @!attribute [rw] ipv6_address
        #   @return [::String]
        #     The IPv6 address assigned to the instance.
        #     (Deprecated) This property was applicable only
        #     to First Generation instances.
        # @!attribute [rw] service_account_email_address
        #   @return [::String]
        #     The service account email address assigned to the instance. <br>This
        #     property is read-only.
        # @!attribute [rw] on_premises_configuration
        #   @return [::Google::Cloud::Sql::V1::OnPremisesConfiguration]
        #     Configuration specific to on-premises instances.
        # @!attribute [rw] replica_configuration
        #   @return [::Google::Cloud::Sql::V1::ReplicaConfiguration]
        #     Configuration specific to failover replicas and read replicas.
        # @!attribute [rw] backend_type
        #   @return [::Google::Cloud::Sql::V1::SqlBackendType]
        #     The backend type.
        #     **SECOND_GEN**: Cloud SQL database instance.
        #     **EXTERNAL**: A database server that is not managed by Google.
        #
        #     This property is read-only; use the **tier** property in the **settings**
        #     object to determine the database type.
        # @!attribute [rw] self_link
        #   @return [::String]
        #     The URI of this resource.
        # @!attribute [rw] suspension_reason
        #   @return [::Array<::Google::Cloud::Sql::V1::SqlSuspensionReason>]
        #     If the instance state is SUSPENDED, the reason for the suspension.
        # @!attribute [rw] connection_name
        #   @return [::String]
        #     Connection name of the Cloud SQL instance used in connection strings.
        # @!attribute [rw] name
        #   @return [::String]
        #     Name of the Cloud SQL instance. This does not include the project ID.
        # @!attribute [rw] region
        #   @return [::String]
        #     The geographical region. Can be:
        #     *  **us-central** (**FIRST_GEN** instances only)
        #     *  **us-central1** (**SECOND_GEN** instances only)
        #     *  **asia-east1** or **europe-west1**.
        #
        #     Defaults to **us-central** or **us-central1** depending on the instance
        #     type. The region cannot be changed after instance creation.
        # @!attribute [rw] gce_zone
        #   @return [::String]
        #     The Compute Engine zone that the instance is currently serving from. This
        #     value could be different from the zone that was specified when the instance
        #     was created if the instance has failed over to its secondary zone.
        # @!attribute [rw] secondary_gce_zone
        #   @return [::String]
        #     The Compute Engine zone that the failover instance is currently serving
        #     from for a regional instance. This value could be different
        #     from the zone that was specified when the instance
        #     was created if the instance has failed over to its secondary/failover zone.
        #     Reserved for future use.
        # @!attribute [rw] disk_encryption_configuration
        #   @return [::Google::Cloud::Sql::V1::DiskEncryptionConfiguration]
        #     Disk encryption configuration specific to an instance.
        # @!attribute [rw] disk_encryption_status
        #   @return [::Google::Cloud::Sql::V1::DiskEncryptionStatus]
        #     Disk encryption status specific to an instance.
        # @!attribute [rw] root_password
        #   @return [::String]
        #     Initial root password. Use only on creation.
        # @!attribute [rw] scheduled_maintenance
        #   @return [::Google::Cloud::Sql::V1::DatabaseInstance::SqlScheduledMaintenance]
        #     The start time of any upcoming scheduled maintenance for this instance.
        # @!attribute [rw] satisfies_pzs
        #   @return [::Google::Protobuf::BoolValue]
        #     The status indicating if instance satisfiesPzs.
        #     Reserved for future use.
        # @!attribute [rw] out_of_disk_report
        #   @return [::Google::Cloud::Sql::V1::DatabaseInstance::SqlOutOfDiskReport]
        #     This field represents the report generated by the proactive database
        #     wellness job for OutOfDisk issues.
        #     *  Writers:
        #       *  the proactive database wellness job for OOD.
        #     *  Readers:
        #       *  the proactive database wellness job
        # @!attribute [r] create_time
        #   @return [::Google::Protobuf::Timestamp]
        #     Output only. The time when the instance was created in
        #     [RFC 3339](https://tools.ietf.org/html/rfc3339) format, for example
        #     **2012-11-15T16:19:00.094Z**.
        class DatabaseInstance
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods

          # @!attribute [rw] name
          #   @return [::String]
          #     The name of the failover replica. If specified at instance creation, a
          #     failover replica is created for the instance. The name
          #     doesn't include the project ID.
          # @!attribute [rw] available
          #   @return [::Google::Protobuf::BoolValue]
          #     The availability status of the failover replica. A false status indicates
          #     that the failover replica is out of sync. The primary instance can only
          #     failover to the failover replica when the status is true.
          class SqlFailoverReplica
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # Any scheduled maintenancce for this instance.
          # @!attribute [rw] start_time
          #   @return [::Google::Protobuf::Timestamp]
          #     The start time of any upcoming scheduled maintenance for this instance.
          # @!attribute [rw] can_defer
          #   @return [::Boolean]
          # @!attribute [rw] can_reschedule
          #   @return [::Boolean]
          #     If the scheduled maintenance can be rescheduled.
          # @!attribute [rw] schedule_deadline_time
          #   @return [::Google::Protobuf::Timestamp]
          #     Maintenance cannot be rescheduled to start beyond this deadline.
          class SqlScheduledMaintenance
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          # This message wraps up the information written by out-of-disk detection job.
          # @!attribute [rw] sql_out_of_disk_state
          #   @return [::Google::Cloud::Sql::V1::DatabaseInstance::SqlOutOfDiskReport::SqlOutOfDiskState]
          #     This field represents the state generated by the proactive database
          #     wellness job for OutOfDisk issues.
          #     *  Writers:
          #       *  the proactive database wellness job for OOD.
          #     *  Readers:
          #       *  the proactive database wellness job
          # @!attribute [rw] sql_min_recommended_increase_size_gb
          #   @return [::Integer]
          #     The minimum recommended increase size in GigaBytes
          #     This field is consumed by the frontend
          #     *  Writers:
          #       *  the proactive database wellness job for OOD.
          #     *  Readers:
          class SqlOutOfDiskReport
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods

            # This enum lists all possible states regarding out-of-disk issues.
            module SqlOutOfDiskState
              # Unspecified state
              SQL_OUT_OF_DISK_STATE_UNSPECIFIED = 0

              # The instance has plenty space on data disk
              NORMAL = 1

              # Data disk is almost used up. It is shutdown to prevent data
              # corruption.
              SOFT_SHUTDOWN = 2
            end
          end

          # The current serving state of the database instance.
          module SqlInstanceState
            # The state of the instance is unknown.
            SQL_INSTANCE_STATE_UNSPECIFIED = 0

            # The instance is running, or has been stopped by owner.
            RUNNABLE = 1

            # The instance is not available, for example due to problems with billing.
            SUSPENDED = 2

            # The instance is being deleted.
            PENDING_DELETE = 3

            # The instance is being created.
            PENDING_CREATE = 4

            # The instance is down for maintenance.
            MAINTENANCE = 5

            # The creation of the instance failed or a fatal error occurred during
            # maintenance.
            FAILED = 6

            # The instance is under maintenance operations and the database is
            # available.
            ONLINE_MAINTENANCE = 7
          end
        end

        # Reschedule options for maintenance windows.
        # @!attribute [rw] reschedule
        #   @return [::Google::Cloud::Sql::V1::SqlInstancesRescheduleMaintenanceRequestBody::Reschedule]
        #     Required. The type of the reschedule the user wants.
        class SqlInstancesRescheduleMaintenanceRequestBody
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods

          # @!attribute [rw] reschedule_type
          #   @return [::Google::Cloud::Sql::V1::SqlInstancesRescheduleMaintenanceRequestBody::RescheduleType]
          #     Required. The type of the reschedule.
          # @!attribute [rw] schedule_time
          #   @return [::Google::Protobuf::Timestamp]
          #     Optional. Timestamp when the maintenance shall be rescheduled to if
          #     reschedule_type=SPECIFIC_TIME, in
          #     [RFC 3339](https://tools.ietf.org/html/rfc3339) format, for example
          #     **2012-11-15T16:19:00.094Z**.
          class Reschedule
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods
          end

          module RescheduleType
            RESCHEDULE_TYPE_UNSPECIFIED = 0

            # Reschedules maintenance to happen now (within 5 minutes).
            IMMEDIATE = 1

            # Reschedules maintenance to occur within one week from the originally
            # scheduled day and time.
            NEXT_AVAILABLE_WINDOW = 2

            # Reschedules maintenance to a specific time and day.
            SPECIFIC_TIME = 3
          end
        end

        # Database instance demote primary instance context.
        # @!attribute [rw] kind
        #   @return [::String]
        #     This is always **sql#demoteMasterContext**.
        # @!attribute [rw] verify_gtid_consistency
        #   @return [::Google::Protobuf::BoolValue]
        #     Verify GTID consistency for demote operation. Default value:
        #     **True**. Setting this flag to false enables you to bypass GTID consistency
        #     check between on-premises primary instance and Cloud SQL instance during
        #     the demotion operation but also exposes you to the risk of future
        #     replication failures. Change the value only if you know the reason for the
        #     GTID divergence and are confident that doing so will not cause any
        #     replication issues.
        # @!attribute [rw] master_instance_name
        #   @return [::String]
        #     The name of the instance which will act as on-premises primary instance
        #     in the replication setup.
        # @!attribute [rw] replica_configuration
        #   @return [::Google::Cloud::Sql::V1::DemoteMasterConfiguration]
        #     Configuration specific to read-replicas replicating from the on-premises
        #     primary instance.
        # @!attribute [rw] skip_replication_setup
        #   @return [::Boolean]
        #     Flag to skip replication setup on the instance.
        class DemoteMasterContext
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Database instance failover context.
        # @!attribute [rw] settings_version
        #   @return [::Integer]
        #     The current settings version of this instance. Request will be rejected if
        #     this version doesn't match the current settings version.
        # @!attribute [rw] kind
        #   @return [::String]
        #     This is always **sql#failoverContext**.
        class FailoverContext
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Database instance restore from backup context.
        # Backup context contains source instance id and project id.
        # @!attribute [rw] kind
        #   @return [::String]
        #     This is always **sql#restoreBackupContext**.
        # @!attribute [rw] backup_run_id
        #   @return [::Integer]
        #     The ID of the backup run to restore from.
        # @!attribute [rw] instance_id
        #   @return [::String]
        #     The ID of the instance that the backup was taken from.
        # @!attribute [rw] project
        #   @return [::String]
        #     The full project ID of the source instance.
        class RestoreBackupContext
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Instance rotate server CA context.
        # @!attribute [rw] kind
        #   @return [::String]
        #     This is always **sql#rotateServerCaContext**.
        # @!attribute [rw] next_version
        #   @return [::String]
        #     The fingerprint of the next version to be rotated to. If left unspecified,
        #     will be rotated to the most recently added server CA version.
        class RotateServerCaContext
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Database Instance truncate log context.
        # @!attribute [rw] kind
        #   @return [::String]
        #     This is always **sql#truncateLogContext**.
        # @!attribute [rw] log_type
        #   @return [::String]
        #     The type of log to truncate. Valid values are **MYSQL_GENERAL_TABLE** and
        #     **MYSQL_SLOW_TABLE**.
        class TruncateLogContext
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # External primary instance migration setting error/warning.
        # @!attribute [rw] kind
        #   @return [::String]
        #     Can be **sql#externalSyncSettingError** or
        #     **sql#externalSyncSettingWarning**.
        # @!attribute [rw] type
        #   @return [::Google::Cloud::Sql::V1::SqlExternalSyncSettingError::SqlExternalSyncSettingErrorType]
        #     Identifies the specific error that occurred.
        # @!attribute [rw] detail
        #   @return [::String]
        #     Additional information about the error encountered.
        class SqlExternalSyncSettingError
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods

          module SqlExternalSyncSettingErrorType
            SQL_EXTERNAL_SYNC_SETTING_ERROR_TYPE_UNSPECIFIED = 0

            CONNECTION_FAILURE = 1

            BINLOG_NOT_ENABLED = 2

            INCOMPATIBLE_DATABASE_VERSION = 3

            REPLICA_ALREADY_SETUP = 4

            INSUFFICIENT_PRIVILEGE = 5

            # Unsupported migration type.
            UNSUPPORTED_MIGRATION_TYPE = 6

            # No pglogical extension installed on databases, applicable for postgres.
            NO_PGLOGICAL_INSTALLED = 7

            # pglogical node already exists on databases, applicable for postgres.
            PGLOGICAL_NODE_ALREADY_EXISTS = 8

            # The value of parameter wal_level is not set to logical.
            INVALID_WAL_LEVEL = 9

            # The value of parameter shared_preload_libraries does not include
            # pglogical.
            INVALID_SHARED_PRELOAD_LIBRARY = 10

            # The value of parameter max_replication_slots is not sufficient.
            INSUFFICIENT_MAX_REPLICATION_SLOTS = 11

            # The value of parameter max_wal_senders is not sufficient.
            INSUFFICIENT_MAX_WAL_SENDERS = 12

            # The value of parameter max_worker_processes is not sufficient.
            INSUFFICIENT_MAX_WORKER_PROCESSES = 13

            # Extensions installed are either not supported or having unsupported
            # versions
            UNSUPPORTED_EXTENSIONS = 14

            # The value of parameter rds.logical_replication is not set to 1.
            INVALID_RDS_LOGICAL_REPLICATION = 15

            # The primary instance logging setup doesn't allow EM sync.
            INVALID_LOGGING_SETUP = 16

            # The primary instance database parameter setup doesn't allow EM sync.
            INVALID_DB_PARAM = 17

            # The gtid_mode is not supported, applicable for MySQL.
            UNSUPPORTED_GTID_MODE = 18

            # SQL Server Agent is not running.
            SQLSERVER_AGENT_NOT_RUNNING = 19

            # The table definition is not support due to missing primary key or replica
            # identity, applicable for postgres.
            UNSUPPORTED_TABLE_DEFINITION = 20

            # The customer has a definer that will break EM setup.
            UNSUPPORTED_DEFINER = 21

            # SQL Server @@SERVERNAME does not match actual host name
            SQLSERVER_SERVERNAME_MISMATCH = 22

            # The primary instance has been setup and will fail the setup.
            PRIMARY_ALREADY_SETUP = 23

            # The primary instance has unsupported binary log format.
            UNSUPPORTED_BINLOG_FORMAT = 24

            # The primary instance's binary log retention setting.
            BINLOG_RETENTION_SETTING = 25
          end
        end

        # On-premises instance configuration.
        # @!attribute [rw] host_port
        #   @return [::String]
        #     The host and port of the on-premises instance in host:port format
        # @!attribute [rw] kind
        #   @return [::String]
        #     This is always **sql#onPremisesConfiguration**.
        # @!attribute [rw] username
        #   @return [::String]
        #     The username for connecting to on-premises instance.
        # @!attribute [rw] password
        #   @return [::String]
        #     The password for connecting to on-premises instance.
        # @!attribute [rw] ca_certificate
        #   @return [::String]
        #     PEM representation of the trusted CA's x509 certificate.
        # @!attribute [rw] client_certificate
        #   @return [::String]
        #     PEM representation of the replica's x509 certificate.
        # @!attribute [rw] client_key
        #   @return [::String]
        #     PEM representation of the replica's private key. The corresponsing public
        #     key is encoded in the client's certificate.
        # @!attribute [rw] dump_file_path
        #   @return [::String]
        #     The dump file to create the Cloud SQL replica.
        # @!attribute [rw] source_instance
        #   @return [::Google::Cloud::Sql::V1::InstanceReference]
        #     The reference to Cloud SQL instance if the source is Cloud SQL.
        class OnPremisesConfiguration
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        # Read-replica configuration for connecting to the primary instance.
        # @!attribute [rw] kind
        #   @return [::String]
        #     This is always **sql#replicaConfiguration**.
        # @!attribute [rw] mysql_replica_configuration
        #   @return [::Google::Cloud::Sql::V1::MySqlReplicaConfiguration]
        #     MySQL specific configuration when replicating from a MySQL on-premises
        #     primary instance. Replication configuration information such as the
        #     username, password, certificates, and keys are not stored in the instance
        #     metadata. The configuration information is used only to set up the
        #     replication connection and is stored by MySQL in a file named
        #     **master.info** in the data directory.
        # @!attribute [rw] failover_target
        #   @return [::Google::Protobuf::BoolValue]
        #     Specifies if the replica is the failover target. If the field is set to
        #     **true** the replica will be designated as a failover replica. In case the
        #     primary instance fails, the replica instance will be promoted as the new
        #     primary instance. Only one replica can be specified as failover target, and
        #     the replica has to be in different zone with the primary instance.
        class ReplicaConfiguration
          include ::Google::Protobuf::MessageExts
          extend ::Google::Protobuf::MessageExts::ClassMethods
        end

        module SqlInstanceType
          # This is an unknown Cloud SQL instance type.
          SQL_INSTANCE_TYPE_UNSPECIFIED = 0

          # A regular Cloud SQL instance.
          CLOUD_SQL_INSTANCE = 1

          # An instance running on the customer's premises that is not managed by
          # Cloud SQL.
          ON_PREMISES_INSTANCE = 2

          # A Cloud SQL instance acting as a read-replica.
          READ_REPLICA_INSTANCE = 3
        end

        # The suspension reason of the database instance if the state is SUSPENDED.
        module SqlSuspensionReason
          # This is an unknown suspension reason.
          SQL_SUSPENSION_REASON_UNSPECIFIED = 0

          # The instance is suspended due to billing issues (for example:, GCP account
          # issue)
          BILLING_ISSUE = 2

          # The instance is suspended due to illegal content (for example:, child
          # pornography, copyrighted material, etc.).
          LEGAL_ISSUE = 3

          # The instance is causing operational issues (for example:, causing the
          # database to crash).
          OPERATIONAL_ISSUE = 4

          # The KMS key used by the instance is either revoked or denied access to
          KMS_KEY_ISSUE = 5
        end
      end
    end
  end
end
