<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/home/enterprise/sdm/v1/smart_device_management_service.proto

namespace Google\Home\Enterprise\Sdm\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response message for SmartDeviceManagementService.ExecuteDeviceCommand
 *
 * Generated from protobuf message <code>google.home.enterprise.sdm.v1.ExecuteDeviceCommandResponse</code>
 */
class ExecuteDeviceCommandResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The results of executing the command.
     *
     * Generated from protobuf field <code>.google.protobuf.Struct results = 1;</code>
     */
    protected $results = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Struct $results
     *           The results of executing the command.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Home\Enterprise\Sdm\V1\SmartDeviceManagementService::initOnce();
        parent::__construct($data);
    }

    /**
     * The results of executing the command.
     *
     * Generated from protobuf field <code>.google.protobuf.Struct results = 1;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getResults()
    {
        return $this->results;
    }

    public function hasResults()
    {
        return isset($this->results);
    }

    public function clearResults()
    {
        unset($this->results);
    }

    /**
     * The results of executing the command.
     *
     * Generated from protobuf field <code>.google.protobuf.Struct results = 1;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setResults($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->results = $var;

        return $this;
    }

}

