# frozen_string_literal: true

# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V6
        module Errors
          # Container for enum describing possible change event errors.
          class ChangeEventErrorEnum
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods

            # Enum describing possible change event errors.
            module ChangeEventError
              # Enum unspecified.
              UNSPECIFIED = 0

              # The received error code is not known in this version.
              UNKNOWN = 1

              # The requested start date is too old. It cannot be older than 30 days.
              START_DATE_TOO_OLD = 2

              # The change_event search request must specify a finite range filter
              # on change_date_time.
              CHANGE_DATE_RANGE_INFINITE = 3

              # The change event search request has specified invalid date time filters
              # that can never logically produce any valid results (for example, start
              # time after end time).
              CHANGE_DATE_RANGE_NEGATIVE = 4

              # The change_event search request must specify a LIMIT.
              LIMIT_NOT_SPECIFIED = 5

              # The LIMIT specified by change_event request should be less than or equal
              # to 10K.
              INVALID_LIMIT_CLAUSE = 6
            end
          end
        end
      end
    end
  end
end
