<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/securitycenter/settings/v1beta1/securitycenter_settings_service.proto

namespace Google\Cloud\SecurityCenter\Settings\V1beta1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response message for BatchGetSettings.
 *
 * Generated from protobuf message <code>google.cloud.securitycenter.settings.v1beta1.BatchGetSettingsResponse</code>
 */
class BatchGetSettingsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Settings requested.
     *
     * Generated from protobuf field <code>repeated .google.cloud.securitycenter.settings.v1beta1.Settings settings = 1;</code>
     */
    private $settings;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Cloud\SecurityCenter\Settings\V1beta1\Settings[]|\Google\Protobuf\Internal\RepeatedField $settings
     *           Settings requested.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Securitycenter\Settings\V1Beta1\SecuritycenterSettingsService::initOnce();
        parent::__construct($data);
    }

    /**
     * Settings requested.
     *
     * Generated from protobuf field <code>repeated .google.cloud.securitycenter.settings.v1beta1.Settings settings = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSettings()
    {
        return $this->settings;
    }

    /**
     * Settings requested.
     *
     * Generated from protobuf field <code>repeated .google.cloud.securitycenter.settings.v1beta1.Settings settings = 1;</code>
     * @param \Google\Cloud\SecurityCenter\Settings\V1beta1\Settings[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSettings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\SecurityCenter\Settings\V1beta1\Settings::class);
        $this->settings = $arr;

        return $this;
    }

}

