# frozen_string_literal: true

# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!


module Google
  module Ads
    module GoogleAds
      module V9
        module Enums
          # Defines the thumbnail to use for In-Display video ads. Note that
          # DEFAULT_THUMBNAIL may have been uploaded by the user while thumbnails 1-3 are
          # auto-generated from the video.
          class VideoThumbnailEnum
            include ::Google::Protobuf::MessageExts
            extend ::Google::Protobuf::MessageExts::ClassMethods

            # Enum listing the possible types of a video thumbnail.
            module VideoThumbnail
              # The type has not been specified.
              UNSPECIFIED = 0

              # The received value is not known in this version.
              # This is a response-only value.
              UNKNOWN = 1

              # The default thumbnail. Can be auto-generated or user-uploaded.
              DEFAULT_THUMBNAIL = 2

              # Thumbnail 1, generated from the video.
              THUMBNAIL_1 = 3

              # Thumbnail 2, generated from the video.
              THUMBNAIL_2 = 4

              # Thumbnail 3, generated from the video.
              THUMBNAIL_3 = 5
            end
          end
        end
      end
    end
  end
end
