<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/gaming/v1beta/game_server_clusters_service.proto

namespace GPBMetadata\Google\Cloud\Gaming\V1Beta;

class GameServerClustersService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\Client::initOnce();
        \GPBMetadata\Google\Cloud\Gaming\V1Beta\GameServerClusters::initOnce();
        \GPBMetadata\Google\Longrunning\Operations::initOnce();
        $pool->internalAddGeneratedFile(
            '
†
=google/cloud/gaming/v1beta/game_server_clusters_service.protogoogle.cloud.gaming.v1betagoogle/api/client.proto5google/cloud/gaming/v1beta/game_server_clusters.proto#google/longrunning/operations.proto2ﬂ
GameServerClustersServiceÂ
ListGameServerClusters9.google.cloud.gaming.v1beta.ListGameServerClustersRequest:.google.cloud.gaming.v1beta.ListGameServerClustersResponse"TÇ”‰ìEC/v1beta/{parent=projects/*/locations/*/realms/*}/gameServerClusters⁄Aparent“
GetGameServerCluster7.google.cloud.gaming.v1beta.GetGameServerClusterRequest-.google.cloud.gaming.v1beta.GameServerCluster"RÇ”‰ìEC/v1beta/{name=projects/*/locations/*/realms/*/gameServerClusters/*}⁄Aname¥
CreateGameServerCluster:.google.cloud.gaming.v1beta.CreateGameServerClusterRequest.google.longrunning.Operation"ΩÇ”‰ìZ"C/v1beta/{parent=projects/*/locations/*/realms/*}/gameServerClusters:game_server_cluster⁄A1parent,game_server_cluster,game_server_cluster_id A&
GameServerClusterOperationMetadataó
PreviewCreateGameServerClusterA.google.cloud.gaming.v1beta.PreviewCreateGameServerClusterRequestB.google.cloud.gaming.v1beta.PreviewCreateGameServerClusterResponse"nÇ”‰ìh"Q/v1beta/{parent=projects/*/locations/*/realms/*}/gameServerClusters:previewCreate:game_server_clusterı
DeleteGameServerCluster:.google.cloud.gaming.v1beta.DeleteGameServerClusterRequest.google.longrunning.Operation"Ç”‰ìE*C/v1beta/{name=projects/*/locations/*/realms/*/gameServerClusters/*}⁄Aname A*
google.protobuf.EmptyOperationMetadataÇ
PreviewDeleteGameServerClusterA.google.cloud.gaming.v1beta.PreviewDeleteGameServerClusterRequestB.google.cloud.gaming.v1beta.PreviewDeleteGameServerClusterResponse"YÇ”‰ìS*Q/v1beta/{name=projects/*/locations/*/realms/*/gameServerClusters/*}:previewDelete∂
UpdateGameServerCluster:.google.cloud.gaming.v1beta.UpdateGameServerClusterRequest.google.longrunning.Operation"øÇ”‰ìn2W/v1beta/{game_server_cluster.name=projects/*/locations/*/realms/*/gameServerClusters/*}:game_server_cluster⁄Agame_server_cluster,update_mask A&
GameServerClusterOperationMetadata¨
PreviewUpdateGameServerClusterA.google.cloud.gaming.v1beta.PreviewUpdateGameServerClusterRequestB.google.cloud.gaming.v1beta.PreviewUpdateGameServerClusterResponse"ÇÇ”‰ì|2e/v1beta/{game_server_cluster.name=projects/*/locations/*/realms/*/gameServerClusters/*}:previewUpdate:game_server_clusterO Agameservices.googleapis.com“A.https://www.googleapis.com/auth/cloud-platformBd
com.google.cloud.gaming.v1betaPZ@google.golang.org/genproto/googleapis/cloud/gaming/v1beta;gamingbproto3'
        , true);

        static::$is_initialized = true;
    }
}

