<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/apps/market/v2/resources.proto

namespace Ccc\Hosted\Marketplace\V2;

if (false) {
    /**
     * This class is deprecated. Use Ccc\Hosted\Marketplace\V2\LicenseNotification\Provisions instead.
     * @deprecated
     */
    class LicenseNotification_Provisions {}
}
class_exists(LicenseNotification\Provisions::class);
@trigger_error('Ccc\Hosted\Marketplace\V2\LicenseNotification_Provisions is deprecated and will be removed in the next major release. Use Ccc\Hosted\Marketplace\V2\LicenseNotification\Provisions instead', E_USER_DEPRECATED);

